//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESIDIFBeneficiarios.service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.en.esidif.mecon.gov.ar", ConfigurationName="service.getBeneficiarioService")]
    public interface getBeneficiarioService {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación getBeneficiario no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="https://ws-si.mecon.gov.ar/ws/entes/getBeneficiarioService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ESIDIFBeneficiarios.service.getBeneficiarioResponse getBeneficiario(ESIDIFBeneficiarios.service.getBeneficiarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ws-si.mecon.gov.ar/ws/entes/getBeneficiarioService", ReplyAction="*")]
        System.Threading.Tasks.Task<ESIDIFBeneficiarios.service.getBeneficiarioResponse> getBeneficiarioAsync(ESIDIFBeneficiarios.service.getBeneficiarioRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webServices.interfazEntes.esidif.mecon.gov.ar")]
    public partial class beneficiarioBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long numeroEnteField;
        
        private bool numeroEnteFieldSpecified;
        
        private string tipoIdentificadorField;
        
        private string codigoIdentificadorField;
        
        private string descripcionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long numeroEnte {
            get {
                return this.numeroEnteField;
            }
            set {
                this.numeroEnteField = value;
                this.RaisePropertyChanged("numeroEnte");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroEnteSpecified {
            get {
                return this.numeroEnteFieldSpecified;
            }
            set {
                this.numeroEnteFieldSpecified = value;
                this.RaisePropertyChanged("numeroEnteSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string tipoIdentificador {
            get {
                return this.tipoIdentificadorField;
            }
            set {
                this.tipoIdentificadorField = value;
                this.RaisePropertyChanged("tipoIdentificador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string codigoIdentificador {
            get {
                return this.codigoIdentificadorField;
            }
            set {
                this.codigoIdentificadorField = value;
                this.RaisePropertyChanged("codigoIdentificador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBeneficiarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.en.esidif.mecon.gov.ar", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string tipoIdentificador;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.en.esidif.mecon.gov.ar", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string codigoIdentificador;
        
        public getBeneficiarioRequest() {
        }
        
        public getBeneficiarioRequest(string tipoIdentificador, string codigoIdentificador) {
            this.tipoIdentificador = tipoIdentificador;
            this.codigoIdentificador = codigoIdentificador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBeneficiarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webServices.interfazEntes.esidif.mecon.gov.ar", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ESIDIFBeneficiarios.service.beneficiarioBean[] getBeneficiario;
        
        public getBeneficiarioResponse() {
        }
        
        public getBeneficiarioResponse(ESIDIFBeneficiarios.service.beneficiarioBean[] getBeneficiario) {
            this.getBeneficiario = getBeneficiario;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface getBeneficiarioServiceChannel : ESIDIFBeneficiarios.service.getBeneficiarioService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getBeneficiarioServiceClient : System.ServiceModel.ClientBase<ESIDIFBeneficiarios.service.getBeneficiarioService>, ESIDIFBeneficiarios.service.getBeneficiarioService {
        
        public getBeneficiarioServiceClient() {
        }
        
        public getBeneficiarioServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public getBeneficiarioServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public getBeneficiarioServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public getBeneficiarioServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ESIDIFBeneficiarios.service.getBeneficiarioResponse ESIDIFBeneficiarios.service.getBeneficiarioService.getBeneficiario(ESIDIFBeneficiarios.service.getBeneficiarioRequest request) {
            return base.Channel.getBeneficiario(request);
        }
        
        public ESIDIFBeneficiarios.service.beneficiarioBean[] getBeneficiario(string tipoIdentificador, string codigoIdentificador) {
            ESIDIFBeneficiarios.service.getBeneficiarioRequest inValue = new ESIDIFBeneficiarios.service.getBeneficiarioRequest();
            inValue.tipoIdentificador = tipoIdentificador;
            inValue.codigoIdentificador = codigoIdentificador;
            ESIDIFBeneficiarios.service.getBeneficiarioResponse retVal = ((ESIDIFBeneficiarios.service.getBeneficiarioService)(this)).getBeneficiario(inValue);
            return retVal.getBeneficiario;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ESIDIFBeneficiarios.service.getBeneficiarioResponse> ESIDIFBeneficiarios.service.getBeneficiarioService.getBeneficiarioAsync(ESIDIFBeneficiarios.service.getBeneficiarioRequest request) {
            return base.Channel.getBeneficiarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<ESIDIFBeneficiarios.service.getBeneficiarioResponse> getBeneficiarioAsync(string tipoIdentificador, string codigoIdentificador) {
            ESIDIFBeneficiarios.service.getBeneficiarioRequest inValue = new ESIDIFBeneficiarios.service.getBeneficiarioRequest();
            inValue.tipoIdentificador = tipoIdentificador;
            inValue.codigoIdentificador = codigoIdentificador;
            return ((ESIDIFBeneficiarios.service.getBeneficiarioService)(this)).getBeneficiarioAsync(inValue);
        }
    }
}
