//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESIDIFLimitativa.service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://impl.service.imputacionesPresupuestarias.esidif.mecon.gov.ar", ConfigurationName="service.consultarLimitativaCreditoService")]
    public interface consultarLimitativaCreditoService {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación consultarLimitativaCredito no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="https://ws-si.mecon.gov.ar/ws/imputaciones_presupuestarias/consultarLimitativaCre" +
            "ditoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ESIDIFLimitativa.service.consultarLimitativaCreditoResponse consultarLimitativaCredito(ESIDIFLimitativa.service.consultarLimitativaCreditoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ws-si.mecon.gov.ar/ws/imputaciones_presupuestarias/consultarLimitativaCre" +
            "ditoService", ReplyAction="*")]
        System.Threading.Tasks.Task<ESIDIFLimitativa.service.consultarLimitativaCreditoResponse> consultarLimitativaCreditoAsync(ESIDIFLimitativa.service.consultarLimitativaCreditoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webService.imputacionesPresupuestarias.esidif.mecon.gov.ar")]
    public partial class imputacionCreditoConsulta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long ejercicioField;
        
        private bool ejercicioFieldSpecified;
        
        private long sectorInstitucionalField;
        
        private bool sectorInstitucionalFieldSpecified;
        
        private long subSectorInstitucionalField;
        
        private bool subSectorInstitucionalFieldSpecified;
        
        private long caracterInstitucionalField;
        
        private bool caracterInstitucionalFieldSpecified;
        
        private long jurisdiccionField;
        
        private bool jurisdiccionFieldSpecified;
        
        private long subJurisdiccionField;
        
        private bool subJurisdiccionFieldSpecified;
        
        private long entidadField;
        
        private bool entidadFieldSpecified;
        
        private long servicioField;
        
        private bool servicioFieldSpecified;
        
        private long programaField;
        
        private bool programaFieldSpecified;
        
        private long subProgramaField;
        
        private bool subProgramaFieldSpecified;
        
        private long proyectoField;
        
        private bool proyectoFieldSpecified;
        
        private long actividadField;
        
        private bool actividadFieldSpecified;
        
        private long obraField;
        
        private bool obraFieldSpecified;
        
        private long incisoField;
        
        private bool incisoFieldSpecified;
        
        private long principalField;
        
        private bool principalFieldSpecified;
        
        private long parcialField;
        
        private bool parcialFieldSpecified;
        
        private long subParcialField;
        
        private bool subParcialFieldSpecified;
        
        private long procedenciaField;
        
        private bool procedenciaFieldSpecified;
        
        private long fuenteField;
        
        private bool fuenteFieldSpecified;
        
        private long monedaField;
        
        private bool monedaFieldSpecified;
        
        private long ubicacionGeograficaField;
        
        private bool ubicacionGeograficaFieldSpecified;
        
        private long entidadOrigenDestinoField;
        
        private bool entidadOrigenDestinoFieldSpecified;
        
        private long prestamoExternoField;
        
        private bool prestamoExternoFieldSpecified;
        
        private long bapinField;
        
        private bool bapinFieldSpecified;
        
        private long clasificadorEconomicoField;
        
        private bool clasificadorEconomicoFieldSpecified;
        
        private long finalidadField;
        
        private bool finalidadFieldSpecified;
        
        private long funcionField;
        
        private bool funcionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long ejercicio {
            get {
                return this.ejercicioField;
            }
            set {
                this.ejercicioField = value;
                this.RaisePropertyChanged("ejercicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ejercicioSpecified {
            get {
                return this.ejercicioFieldSpecified;
            }
            set {
                this.ejercicioFieldSpecified = value;
                this.RaisePropertyChanged("ejercicioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long sectorInstitucional {
            get {
                return this.sectorInstitucionalField;
            }
            set {
                this.sectorInstitucionalField = value;
                this.RaisePropertyChanged("sectorInstitucional");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sectorInstitucionalSpecified {
            get {
                return this.sectorInstitucionalFieldSpecified;
            }
            set {
                this.sectorInstitucionalFieldSpecified = value;
                this.RaisePropertyChanged("sectorInstitucionalSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long subSectorInstitucional {
            get {
                return this.subSectorInstitucionalField;
            }
            set {
                this.subSectorInstitucionalField = value;
                this.RaisePropertyChanged("subSectorInstitucional");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool subSectorInstitucionalSpecified {
            get {
                return this.subSectorInstitucionalFieldSpecified;
            }
            set {
                this.subSectorInstitucionalFieldSpecified = value;
                this.RaisePropertyChanged("subSectorInstitucionalSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public long caracterInstitucional {
            get {
                return this.caracterInstitucionalField;
            }
            set {
                this.caracterInstitucionalField = value;
                this.RaisePropertyChanged("caracterInstitucional");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool caracterInstitucionalSpecified {
            get {
                return this.caracterInstitucionalFieldSpecified;
            }
            set {
                this.caracterInstitucionalFieldSpecified = value;
                this.RaisePropertyChanged("caracterInstitucionalSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public long jurisdiccion {
            get {
                return this.jurisdiccionField;
            }
            set {
                this.jurisdiccionField = value;
                this.RaisePropertyChanged("jurisdiccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool jurisdiccionSpecified {
            get {
                return this.jurisdiccionFieldSpecified;
            }
            set {
                this.jurisdiccionFieldSpecified = value;
                this.RaisePropertyChanged("jurisdiccionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public long subJurisdiccion {
            get {
                return this.subJurisdiccionField;
            }
            set {
                this.subJurisdiccionField = value;
                this.RaisePropertyChanged("subJurisdiccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool subJurisdiccionSpecified {
            get {
                return this.subJurisdiccionFieldSpecified;
            }
            set {
                this.subJurisdiccionFieldSpecified = value;
                this.RaisePropertyChanged("subJurisdiccionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public long entidad {
            get {
                return this.entidadField;
            }
            set {
                this.entidadField = value;
                this.RaisePropertyChanged("entidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool entidadSpecified {
            get {
                return this.entidadFieldSpecified;
            }
            set {
                this.entidadFieldSpecified = value;
                this.RaisePropertyChanged("entidadSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public long servicio {
            get {
                return this.servicioField;
            }
            set {
                this.servicioField = value;
                this.RaisePropertyChanged("servicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool servicioSpecified {
            get {
                return this.servicioFieldSpecified;
            }
            set {
                this.servicioFieldSpecified = value;
                this.RaisePropertyChanged("servicioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public long programa {
            get {
                return this.programaField;
            }
            set {
                this.programaField = value;
                this.RaisePropertyChanged("programa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool programaSpecified {
            get {
                return this.programaFieldSpecified;
            }
            set {
                this.programaFieldSpecified = value;
                this.RaisePropertyChanged("programaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public long subPrograma {
            get {
                return this.subProgramaField;
            }
            set {
                this.subProgramaField = value;
                this.RaisePropertyChanged("subPrograma");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool subProgramaSpecified {
            get {
                return this.subProgramaFieldSpecified;
            }
            set {
                this.subProgramaFieldSpecified = value;
                this.RaisePropertyChanged("subProgramaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public long proyecto {
            get {
                return this.proyectoField;
            }
            set {
                this.proyectoField = value;
                this.RaisePropertyChanged("proyecto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool proyectoSpecified {
            get {
                return this.proyectoFieldSpecified;
            }
            set {
                this.proyectoFieldSpecified = value;
                this.RaisePropertyChanged("proyectoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public long actividad {
            get {
                return this.actividadField;
            }
            set {
                this.actividadField = value;
                this.RaisePropertyChanged("actividad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool actividadSpecified {
            get {
                return this.actividadFieldSpecified;
            }
            set {
                this.actividadFieldSpecified = value;
                this.RaisePropertyChanged("actividadSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public long obra {
            get {
                return this.obraField;
            }
            set {
                this.obraField = value;
                this.RaisePropertyChanged("obra");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool obraSpecified {
            get {
                return this.obraFieldSpecified;
            }
            set {
                this.obraFieldSpecified = value;
                this.RaisePropertyChanged("obraSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public long inciso {
            get {
                return this.incisoField;
            }
            set {
                this.incisoField = value;
                this.RaisePropertyChanged("inciso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool incisoSpecified {
            get {
                return this.incisoFieldSpecified;
            }
            set {
                this.incisoFieldSpecified = value;
                this.RaisePropertyChanged("incisoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public long principal {
            get {
                return this.principalField;
            }
            set {
                this.principalField = value;
                this.RaisePropertyChanged("principal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool principalSpecified {
            get {
                return this.principalFieldSpecified;
            }
            set {
                this.principalFieldSpecified = value;
                this.RaisePropertyChanged("principalSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public long parcial {
            get {
                return this.parcialField;
            }
            set {
                this.parcialField = value;
                this.RaisePropertyChanged("parcial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool parcialSpecified {
            get {
                return this.parcialFieldSpecified;
            }
            set {
                this.parcialFieldSpecified = value;
                this.RaisePropertyChanged("parcialSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public long subParcial {
            get {
                return this.subParcialField;
            }
            set {
                this.subParcialField = value;
                this.RaisePropertyChanged("subParcial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool subParcialSpecified {
            get {
                return this.subParcialFieldSpecified;
            }
            set {
                this.subParcialFieldSpecified = value;
                this.RaisePropertyChanged("subParcialSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public long procedencia {
            get {
                return this.procedenciaField;
            }
            set {
                this.procedenciaField = value;
                this.RaisePropertyChanged("procedencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool procedenciaSpecified {
            get {
                return this.procedenciaFieldSpecified;
            }
            set {
                this.procedenciaFieldSpecified = value;
                this.RaisePropertyChanged("procedenciaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public long fuente {
            get {
                return this.fuenteField;
            }
            set {
                this.fuenteField = value;
                this.RaisePropertyChanged("fuente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fuenteSpecified {
            get {
                return this.fuenteFieldSpecified;
            }
            set {
                this.fuenteFieldSpecified = value;
                this.RaisePropertyChanged("fuenteSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public long moneda {
            get {
                return this.monedaField;
            }
            set {
                this.monedaField = value;
                this.RaisePropertyChanged("moneda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool monedaSpecified {
            get {
                return this.monedaFieldSpecified;
            }
            set {
                this.monedaFieldSpecified = value;
                this.RaisePropertyChanged("monedaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public long ubicacionGeografica {
            get {
                return this.ubicacionGeograficaField;
            }
            set {
                this.ubicacionGeograficaField = value;
                this.RaisePropertyChanged("ubicacionGeografica");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ubicacionGeograficaSpecified {
            get {
                return this.ubicacionGeograficaFieldSpecified;
            }
            set {
                this.ubicacionGeograficaFieldSpecified = value;
                this.RaisePropertyChanged("ubicacionGeograficaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public long entidadOrigenDestino {
            get {
                return this.entidadOrigenDestinoField;
            }
            set {
                this.entidadOrigenDestinoField = value;
                this.RaisePropertyChanged("entidadOrigenDestino");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool entidadOrigenDestinoSpecified {
            get {
                return this.entidadOrigenDestinoFieldSpecified;
            }
            set {
                this.entidadOrigenDestinoFieldSpecified = value;
                this.RaisePropertyChanged("entidadOrigenDestinoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public long prestamoExterno {
            get {
                return this.prestamoExternoField;
            }
            set {
                this.prestamoExternoField = value;
                this.RaisePropertyChanged("prestamoExterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool prestamoExternoSpecified {
            get {
                return this.prestamoExternoFieldSpecified;
            }
            set {
                this.prestamoExternoFieldSpecified = value;
                this.RaisePropertyChanged("prestamoExternoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public long bapin {
            get {
                return this.bapinField;
            }
            set {
                this.bapinField = value;
                this.RaisePropertyChanged("bapin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bapinSpecified {
            get {
                return this.bapinFieldSpecified;
            }
            set {
                this.bapinFieldSpecified = value;
                this.RaisePropertyChanged("bapinSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public long clasificadorEconomico {
            get {
                return this.clasificadorEconomicoField;
            }
            set {
                this.clasificadorEconomicoField = value;
                this.RaisePropertyChanged("clasificadorEconomico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool clasificadorEconomicoSpecified {
            get {
                return this.clasificadorEconomicoFieldSpecified;
            }
            set {
                this.clasificadorEconomicoFieldSpecified = value;
                this.RaisePropertyChanged("clasificadorEconomicoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public long finalidad {
            get {
                return this.finalidadField;
            }
            set {
                this.finalidadField = value;
                this.RaisePropertyChanged("finalidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool finalidadSpecified {
            get {
                return this.finalidadFieldSpecified;
            }
            set {
                this.finalidadFieldSpecified = value;
                this.RaisePropertyChanged("finalidadSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public long funcion {
            get {
                return this.funcionField;
            }
            set {
                this.funcionField = value;
                this.RaisePropertyChanged("funcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool funcionSpecified {
            get {
                return this.funcionFieldSpecified;
            }
            set {
                this.funcionFieldSpecified = value;
                this.RaisePropertyChanged("funcionSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarLimitativaCreditoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webService.imputacionesPresupuestarias.esidif.mecon.gov.ar", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ESIDIFLimitativa.service.imputacionCreditoConsulta imputacionPresupuestariaCreditoIndicativa;
        
        public consultarLimitativaCreditoRequest() {
        }
        
        public consultarLimitativaCreditoRequest(ESIDIFLimitativa.service.imputacionCreditoConsulta imputacionPresupuestariaCreditoIndicativa) {
            this.imputacionPresupuestariaCreditoIndicativa = imputacionPresupuestariaCreditoIndicativa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarLimitativaCreditoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webService.imputacionesPresupuestarias.esidif.mecon.gov.ar", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ESIDIFLimitativa.service.imputacionCreditoConsulta imputacionPresupuestarioCreditoLimitativa;
        
        public consultarLimitativaCreditoResponse() {
        }
        
        public consultarLimitativaCreditoResponse(ESIDIFLimitativa.service.imputacionCreditoConsulta imputacionPresupuestarioCreditoLimitativa) {
            this.imputacionPresupuestarioCreditoLimitativa = imputacionPresupuestarioCreditoLimitativa;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface consultarLimitativaCreditoServiceChannel : ESIDIFLimitativa.service.consultarLimitativaCreditoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class consultarLimitativaCreditoServiceClient : System.ServiceModel.ClientBase<ESIDIFLimitativa.service.consultarLimitativaCreditoService>, ESIDIFLimitativa.service.consultarLimitativaCreditoService {
        
        public consultarLimitativaCreditoServiceClient() {
        }
        
        public consultarLimitativaCreditoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public consultarLimitativaCreditoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public consultarLimitativaCreditoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public consultarLimitativaCreditoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ESIDIFLimitativa.service.consultarLimitativaCreditoResponse ESIDIFLimitativa.service.consultarLimitativaCreditoService.consultarLimitativaCredito(ESIDIFLimitativa.service.consultarLimitativaCreditoRequest request) {
            return base.Channel.consultarLimitativaCredito(request);
        }
        
        public ESIDIFLimitativa.service.imputacionCreditoConsulta consultarLimitativaCredito(ESIDIFLimitativa.service.imputacionCreditoConsulta imputacionPresupuestariaCreditoIndicativa) {
            ESIDIFLimitativa.service.consultarLimitativaCreditoRequest inValue = new ESIDIFLimitativa.service.consultarLimitativaCreditoRequest();
            inValue.imputacionPresupuestariaCreditoIndicativa = imputacionPresupuestariaCreditoIndicativa;
            ESIDIFLimitativa.service.consultarLimitativaCreditoResponse retVal = ((ESIDIFLimitativa.service.consultarLimitativaCreditoService)(this)).consultarLimitativaCredito(inValue);
            return retVal.imputacionPresupuestarioCreditoLimitativa;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ESIDIFLimitativa.service.consultarLimitativaCreditoResponse> ESIDIFLimitativa.service.consultarLimitativaCreditoService.consultarLimitativaCreditoAsync(ESIDIFLimitativa.service.consultarLimitativaCreditoRequest request) {
            return base.Channel.consultarLimitativaCreditoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ESIDIFLimitativa.service.consultarLimitativaCreditoResponse> consultarLimitativaCreditoAsync(ESIDIFLimitativa.service.imputacionCreditoConsulta imputacionPresupuestariaCreditoIndicativa) {
            ESIDIFLimitativa.service.consultarLimitativaCreditoRequest inValue = new ESIDIFLimitativa.service.consultarLimitativaCreditoRequest();
            inValue.imputacionPresupuestariaCreditoIndicativa = imputacionPresupuestariaCreditoIndicativa;
            return ((ESIDIFLimitativa.service.consultarLimitativaCreditoService)(this)).consultarLimitativaCreditoAsync(inValue);
        }
    }
}
