//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESIDIFC75.service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://ws-si.mecon.gov.ar/ws/generarInformeDeGastos", ConfigurationName="service.generarInformeDeGastosPortType")]
    public interface generarInformeDeGastosPortType {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación generarInformeDeGastos no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="https://ws-si.mecon.gov.ar/ws/gastos/informeDeGastos/generarInformeDeGastosServic" +
            "e", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ESIDIFC75.service.generarInformeDeGastosResponse1 generarInformeDeGastos(ESIDIFC75.service.generarInformeDeGastosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ws-si.mecon.gov.ar/ws/gastos/informeDeGastos/generarInformeDeGastosServic" +
            "e", ReplyAction="*")]
        System.Threading.Tasks.Task<ESIDIFC75.service.generarInformeDeGastosResponse1> generarInformeDeGastosAsync(ESIDIFC75.service.generarInformeDeGastosRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://ws-si.mecon.gov.ar/ws/informeDeGastosMsg")]
    public partial class generarInformeDeGastos : object, System.ComponentModel.INotifyPropertyChanged {
        
        private DatosInicialesInformeDeGastosType datosInicialesInformeDeGastosField;
        
        private GestionExternaEnum gestionExternaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public DatosInicialesInformeDeGastosType datosInicialesInformeDeGastos {
            get {
                return this.datosInicialesInformeDeGastosField;
            }
            set {
                this.datosInicialesInformeDeGastosField = value;
                this.RaisePropertyChanged("datosInicialesInformeDeGastos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public GestionExternaEnum gestionExterna {
            get {
                return this.gestionExternaField;
            }
            set {
                this.gestionExternaField = value;
                this.RaisePropertyChanged("gestionExterna");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ws-si.mecon.gov.ar/ws/informeDeGastos")]
    public partial class DatosInicialesInformeDeGastosType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private IdentificacionComprobanteType identificacionComprobanteField;
        
        private string entidadProcesoField;
        
        private IdentificadorDeTramiteType identificadorTramiteField;
        
        private DocumentoRespaldatorioType documentoRespaldatorioField;
        
        private IdentificacionComprobanteType comprobanteOrigenField;
        
        private System.DateTime fechaAutorizacionField;
        
        private System.DateTime fechaComprobanteField;
        
        private System.DateTime fechaRegistroField;
        
        private bool fechaRegistroFieldSpecified;
        
        private int periodoImpactoField;
        
        private bool periodoImpactoFieldSpecified;
        
        private CuentaType cuentaFinanciadoraField;
        
        private bool pagoDirectoField;
        
        private MedioDePagoType medioDePagoField;
        
        private decimal importeCompromisoField;
        
        private decimal importeDevengadoField;
        
        private decimal importePagadoField;
        
        private decimal importeDeduccionesField;
        
        private decimal importeDeduccionesPagadoField;
        
        private decimal importeNetoPagadoField;
        
        private string uepexField;
        
        private string observacionesField;
        
        private ItemPresupuestarioInformeDeGastosType[] itemsPresupuestariosField;
        
        private ItemNoPresupuestarioInformeDeGastosType[] itemsNoPresupuestariosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public IdentificacionComprobanteType identificacionComprobante {
            get {
                return this.identificacionComprobanteField;
            }
            set {
                this.identificacionComprobanteField = value;
                this.RaisePropertyChanged("identificacionComprobante");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string entidadProceso {
            get {
                return this.entidadProcesoField;
            }
            set {
                this.entidadProcesoField = value;
                this.RaisePropertyChanged("entidadProceso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public IdentificadorDeTramiteType identificadorTramite {
            get {
                return this.identificadorTramiteField;
            }
            set {
                this.identificadorTramiteField = value;
                this.RaisePropertyChanged("identificadorTramite");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public DocumentoRespaldatorioType documentoRespaldatorio {
            get {
                return this.documentoRespaldatorioField;
            }
            set {
                this.documentoRespaldatorioField = value;
                this.RaisePropertyChanged("documentoRespaldatorio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public IdentificacionComprobanteType comprobanteOrigen {
            get {
                return this.comprobanteOrigenField;
            }
            set {
                this.comprobanteOrigenField = value;
                this.RaisePropertyChanged("comprobanteOrigen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=5)]
        public System.DateTime fechaAutorizacion {
            get {
                return this.fechaAutorizacionField;
            }
            set {
                this.fechaAutorizacionField = value;
                this.RaisePropertyChanged("fechaAutorizacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=6)]
        public System.DateTime fechaComprobante {
            get {
                return this.fechaComprobanteField;
            }
            set {
                this.fechaComprobanteField = value;
                this.RaisePropertyChanged("fechaComprobante");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=7)]
        public System.DateTime fechaRegistro {
            get {
                return this.fechaRegistroField;
            }
            set {
                this.fechaRegistroField = value;
                this.RaisePropertyChanged("fechaRegistro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaRegistroSpecified {
            get {
                return this.fechaRegistroFieldSpecified;
            }
            set {
                this.fechaRegistroFieldSpecified = value;
                this.RaisePropertyChanged("fechaRegistroSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int periodoImpacto {
            get {
                return this.periodoImpactoField;
            }
            set {
                this.periodoImpactoField = value;
                this.RaisePropertyChanged("periodoImpacto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool periodoImpactoSpecified {
            get {
                return this.periodoImpactoFieldSpecified;
            }
            set {
                this.periodoImpactoFieldSpecified = value;
                this.RaisePropertyChanged("periodoImpactoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public CuentaType cuentaFinanciadora {
            get {
                return this.cuentaFinanciadoraField;
            }
            set {
                this.cuentaFinanciadoraField = value;
                this.RaisePropertyChanged("cuentaFinanciadora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool pagoDirecto {
            get {
                return this.pagoDirectoField;
            }
            set {
                this.pagoDirectoField = value;
                this.RaisePropertyChanged("pagoDirecto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public MedioDePagoType medioDePago {
            get {
                return this.medioDePagoField;
            }
            set {
                this.medioDePagoField = value;
                this.RaisePropertyChanged("medioDePago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public decimal importeCompromiso {
            get {
                return this.importeCompromisoField;
            }
            set {
                this.importeCompromisoField = value;
                this.RaisePropertyChanged("importeCompromiso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public decimal importeDevengado {
            get {
                return this.importeDevengadoField;
            }
            set {
                this.importeDevengadoField = value;
                this.RaisePropertyChanged("importeDevengado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public decimal importePagado {
            get {
                return this.importePagadoField;
            }
            set {
                this.importePagadoField = value;
                this.RaisePropertyChanged("importePagado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public decimal importeDeducciones {
            get {
                return this.importeDeduccionesField;
            }
            set {
                this.importeDeduccionesField = value;
                this.RaisePropertyChanged("importeDeducciones");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public decimal importeDeduccionesPagado {
            get {
                return this.importeDeduccionesPagadoField;
            }
            set {
                this.importeDeduccionesPagadoField = value;
                this.RaisePropertyChanged("importeDeduccionesPagado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public decimal importeNetoPagado {
            get {
                return this.importeNetoPagadoField;
            }
            set {
                this.importeNetoPagadoField = value;
                this.RaisePropertyChanged("importeNetoPagado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string uepex {
            get {
                return this.uepexField;
            }
            set {
                this.uepexField = value;
                this.RaisePropertyChanged("uepex");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string observaciones {
            get {
                return this.observacionesField;
            }
            set {
                this.observacionesField = value;
                this.RaisePropertyChanged("observaciones");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("itemsPresupuestarios", Order=20)]
        public ItemPresupuestarioInformeDeGastosType[] itemsPresupuestarios {
            get {
                return this.itemsPresupuestariosField;
            }
            set {
                this.itemsPresupuestariosField = value;
                this.RaisePropertyChanged("itemsPresupuestarios");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("itemsNoPresupuestarios", Order=21)]
        public ItemNoPresupuestarioInformeDeGastosType[] itemsNoPresupuestarios {
            get {
                return this.itemsNoPresupuestariosField;
            }
            set {
                this.itemsNoPresupuestariosField = value;
                this.RaisePropertyChanged("itemsNoPresupuestarios");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ws-si.mecon.gov.ar/ws/comprobantes")]
    public partial class IdentificacionComprobanteType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tipoComprobanteField;
        
        private long numeroField;
        
        private long ejercicioField;
        
        private string entidadEmisoraField;
        
        private string tipoRegistroField;
        
        private string subTipoRegistroField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string tipoComprobante {
            get {
                return this.tipoComprobanteField;
            }
            set {
                this.tipoComprobanteField = value;
                this.RaisePropertyChanged("tipoComprobante");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
                this.RaisePropertyChanged("numero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long ejercicio {
            get {
                return this.ejercicioField;
            }
            set {
                this.ejercicioField = value;
                this.RaisePropertyChanged("ejercicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string entidadEmisora {
            get {
                return this.entidadEmisoraField;
            }
            set {
                this.entidadEmisoraField = value;
                this.RaisePropertyChanged("entidadEmisora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string tipoRegistro {
            get {
                return this.tipoRegistroField;
            }
            set {
                this.tipoRegistroField = value;
                this.RaisePropertyChanged("tipoRegistro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string subTipoRegistro {
            get {
                return this.subTipoRegistroField;
            }
            set {
                this.subTipoRegistroField = value;
                this.RaisePropertyChanged("subTipoRegistro");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ws-si.mecon.gov.ar/ws/informeDeGastos")]
    public partial class ItemNoPresupuestarioInformeDeGastosType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long axtField;
        
        private decimal importeDevengadoField;
        
        private decimal importePagadoField;
        
        private long ejercicioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long axt {
            get {
                return this.axtField;
            }
            set {
                this.axtField = value;
                this.RaisePropertyChanged("axt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal importeDevengado {
            get {
                return this.importeDevengadoField;
            }
            set {
                this.importeDevengadoField = value;
                this.RaisePropertyChanged("importeDevengado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal importePagado {
            get {
                return this.importePagadoField;
            }
            set {
                this.importePagadoField = value;
                this.RaisePropertyChanged("importePagado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public long ejercicio {
            get {
                return this.ejercicioField;
            }
            set {
                this.ejercicioField = value;
                this.RaisePropertyChanged("ejercicio");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ws-si.mecon.gov.ar/ws/comprobantes")]
    public partial class CodigoTramoPartidaType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string tramoField;
        
        private string partidaField;
        
        private string codigoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string tramo {
            get {
                return this.tramoField;
            }
            set {
                this.tramoField = value;
                this.RaisePropertyChanged("tramo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string partida {
            get {
                return this.partidaField;
            }
            set {
                this.partidaField = value;
                this.RaisePropertyChanged("partida");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ws-si.mecon.gov.ar/ws/comprobantes")]
    public partial class UnidadDescentralizadaType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private long ejercicioField;
        
        private bool ejercicioFieldSpecified;
        
        private string safField;
        
        private string descripcionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long ejercicio {
            get {
                return this.ejercicioField;
            }
            set {
                this.ejercicioField = value;
                this.RaisePropertyChanged("ejercicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ejercicioSpecified {
            get {
                return this.ejercicioFieldSpecified;
            }
            set {
                this.ejercicioFieldSpecified = value;
                this.RaisePropertyChanged("ejercicioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string saf {
            get {
                return this.safField;
            }
            set {
                this.safField = value;
                this.RaisePropertyChanged("saf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ws-si.mecon.gov.ar/ws/comprobantes")]
    public partial class ImputacionPresupuestariaCreditoType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string institucionField;
        
        private long ejercicioField;
        
        private string servicioField;
        
        private string aperturaProgField;
        
        private string objetoGastoField;
        
        private string fuenteField;
        
        private string monedaField;
        
        private string ugField;
        
        private string entidadDestinoField;
        
        private long bapinField;
        
        private bool bapinFieldSpecified;
        
        private long pexField;
        
        private bool pexFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string institucion {
            get {
                return this.institucionField;
            }
            set {
                this.institucionField = value;
                this.RaisePropertyChanged("institucion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long ejercicio {
            get {
                return this.ejercicioField;
            }
            set {
                this.ejercicioField = value;
                this.RaisePropertyChanged("ejercicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string servicio {
            get {
                return this.servicioField;
            }
            set {
                this.servicioField = value;
                this.RaisePropertyChanged("servicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string aperturaProg {
            get {
                return this.aperturaProgField;
            }
            set {
                this.aperturaProgField = value;
                this.RaisePropertyChanged("aperturaProg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string objetoGasto {
            get {
                return this.objetoGastoField;
            }
            set {
                this.objetoGastoField = value;
                this.RaisePropertyChanged("objetoGasto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string fuente {
            get {
                return this.fuenteField;
            }
            set {
                this.fuenteField = value;
                this.RaisePropertyChanged("fuente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string moneda {
            get {
                return this.monedaField;
            }
            set {
                this.monedaField = value;
                this.RaisePropertyChanged("moneda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ug {
            get {
                return this.ugField;
            }
            set {
                this.ugField = value;
                this.RaisePropertyChanged("ug");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string entidadDestino {
            get {
                return this.entidadDestinoField;
            }
            set {
                this.entidadDestinoField = value;
                this.RaisePropertyChanged("entidadDestino");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public long bapin {
            get {
                return this.bapinField;
            }
            set {
                this.bapinField = value;
                this.RaisePropertyChanged("bapin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bapinSpecified {
            get {
                return this.bapinFieldSpecified;
            }
            set {
                this.bapinFieldSpecified = value;
                this.RaisePropertyChanged("bapinSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public long pex {
            get {
                return this.pexField;
            }
            set {
                this.pexField = value;
                this.RaisePropertyChanged("pex");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pexSpecified {
            get {
                return this.pexFieldSpecified;
            }
            set {
                this.pexFieldSpecified = value;
                this.RaisePropertyChanged("pexSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ws-si.mecon.gov.ar/ws/informeDeGastos")]
    public partial class ItemPresupuestarioInformeDeGastosType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ImputacionPresupuestariaCreditoType imputacionField;
        
        private UnidadDescentralizadaType udField;
        
        private CodigoTramoPartidaType recacField;
        
        private CodigoTramoPartidaType sigadeField;
        
        private decimal importeCompromisoField;
        
        private decimal importeDevengadoField;
        
        private decimal importePagadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ImputacionPresupuestariaCreditoType imputacion {
            get {
                return this.imputacionField;
            }
            set {
                this.imputacionField = value;
                this.RaisePropertyChanged("imputacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public UnidadDescentralizadaType ud {
            get {
                return this.udField;
            }
            set {
                this.udField = value;
                this.RaisePropertyChanged("ud");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public CodigoTramoPartidaType recac {
            get {
                return this.recacField;
            }
            set {
                this.recacField = value;
                this.RaisePropertyChanged("recac");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public CodigoTramoPartidaType sigade {
            get {
                return this.sigadeField;
            }
            set {
                this.sigadeField = value;
                this.RaisePropertyChanged("sigade");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal importeCompromiso {
            get {
                return this.importeCompromisoField;
            }
            set {
                this.importeCompromisoField = value;
                this.RaisePropertyChanged("importeCompromiso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public decimal importeDevengado {
            get {
                return this.importeDevengadoField;
            }
            set {
                this.importeDevengadoField = value;
                this.RaisePropertyChanged("importeDevengado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public decimal importePagado {
            get {
                return this.importePagadoField;
            }
            set {
                this.importePagadoField = value;
                this.RaisePropertyChanged("importePagado");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ws-si.mecon.gov.ar/ws/comprobantes")]
    public partial class CuentaType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long bancoField;
        
        private string sucursalField;
        
        private string cuentaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long banco {
            get {
                return this.bancoField;
            }
            set {
                this.bancoField = value;
                this.RaisePropertyChanged("banco");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string sucursal {
            get {
                return this.sucursalField;
            }
            set {
                this.sucursalField = value;
                this.RaisePropertyChanged("sucursal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string cuenta {
            get {
                return this.cuentaField;
            }
            set {
                this.cuentaField = value;
                this.RaisePropertyChanged("cuenta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ws-si.mecon.gov.ar/ws/comprobantes")]
    public partial class DocumentoRespaldatorioType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tipoField;
        
        private long numeroField;
        
        private long ejercicioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
                this.RaisePropertyChanged("numero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long ejercicio {
            get {
                return this.ejercicioField;
            }
            set {
                this.ejercicioField = value;
                this.RaisePropertyChanged("ejercicio");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ws-si.mecon.gov.ar/ws/comprobantes")]
    public partial class IdentificadorDeTramiteType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tipoField;
        
        private string identificadorField;
        
        private long anioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string identificador {
            get {
                return this.identificadorField;
            }
            set {
                this.identificadorField = value;
                this.RaisePropertyChanged("identificador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long anio {
            get {
                return this.anioField;
            }
            set {
                this.anioField = value;
                this.RaisePropertyChanged("anio");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ws-si.mecon.gov.ar/ws/comprobantes")]
    public enum MedioDePagoType {
        
        /// <remarks/>
        CHE,
        
        /// <remarks/>
        EX,
        
        /// <remarks/>
        DB,
        
        /// <remarks/>
        OV,
        
        /// <remarks/>
        OR,
        
        /// <remarks/>
        BC,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ws-si.mecon.gov.ar/ws/comprobantes")]
    public enum GestionExternaEnum {
        
        /// <remarks/>
        LOYS_2345,
        
        /// <remarks/>
        LOYS_AT,
        
        /// <remarks/>
        GAT,
        
        /// <remarks/>
        UEPEX,
        
        /// <remarks/>
        ANSES,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://ws-si.mecon.gov.ar/ws/informeDeGastosMsg")]
    public partial class generarInformeDeGastosResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long numeroSidifField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long numeroSidif {
            get {
                return this.numeroSidifField;
            }
            set {
                this.numeroSidifField = value;
                this.RaisePropertyChanged("numeroSidif");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generarInformeDeGastosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://ws-si.mecon.gov.ar/ws/informeDeGastosMsg", Order=0)]
        public ESIDIFC75.service.generarInformeDeGastos generarInformeDeGastos;
        
        public generarInformeDeGastosRequest() {
        }
        
        public generarInformeDeGastosRequest(ESIDIFC75.service.generarInformeDeGastos generarInformeDeGastos) {
            this.generarInformeDeGastos = generarInformeDeGastos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generarInformeDeGastosResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://ws-si.mecon.gov.ar/ws/informeDeGastosMsg", Order=0)]
        public ESIDIFC75.service.generarInformeDeGastosResponse generarInformeDeGastosResponse;
        
        public generarInformeDeGastosResponse1() {
        }
        
        public generarInformeDeGastosResponse1(ESIDIFC75.service.generarInformeDeGastosResponse generarInformeDeGastosResponse) {
            this.generarInformeDeGastosResponse = generarInformeDeGastosResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface generarInformeDeGastosPortTypeChannel : ESIDIFC75.service.generarInformeDeGastosPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class generarInformeDeGastosPortTypeClient : System.ServiceModel.ClientBase<ESIDIFC75.service.generarInformeDeGastosPortType>, ESIDIFC75.service.generarInformeDeGastosPortType {
        
        public generarInformeDeGastosPortTypeClient() {
        }
        
        public generarInformeDeGastosPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public generarInformeDeGastosPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public generarInformeDeGastosPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public generarInformeDeGastosPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ESIDIFC75.service.generarInformeDeGastosResponse1 ESIDIFC75.service.generarInformeDeGastosPortType.generarInformeDeGastos(ESIDIFC75.service.generarInformeDeGastosRequest request) {
            return base.Channel.generarInformeDeGastos(request);
        }
        
        public ESIDIFC75.service.generarInformeDeGastosResponse generarInformeDeGastos(ESIDIFC75.service.generarInformeDeGastos generarInformeDeGastos1) {
            ESIDIFC75.service.generarInformeDeGastosRequest inValue = new ESIDIFC75.service.generarInformeDeGastosRequest();
            inValue.generarInformeDeGastos = generarInformeDeGastos1;
            ESIDIFC75.service.generarInformeDeGastosResponse1 retVal = ((ESIDIFC75.service.generarInformeDeGastosPortType)(this)).generarInformeDeGastos(inValue);
            return retVal.generarInformeDeGastosResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ESIDIFC75.service.generarInformeDeGastosResponse1> ESIDIFC75.service.generarInformeDeGastosPortType.generarInformeDeGastosAsync(ESIDIFC75.service.generarInformeDeGastosRequest request) {
            return base.Channel.generarInformeDeGastosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ESIDIFC75.service.generarInformeDeGastosResponse1> generarInformeDeGastosAsync(ESIDIFC75.service.generarInformeDeGastos generarInformeDeGastos) {
            ESIDIFC75.service.generarInformeDeGastosRequest inValue = new ESIDIFC75.service.generarInformeDeGastosRequest();
            inValue.generarInformeDeGastos = generarInformeDeGastos;
            return ((ESIDIFC75.service.generarInformeDeGastosPortType)(this)).generarInformeDeGastosAsync(inValue);
        }
    }
}
