//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESIDIFCredito.service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", ConfigurationName="service.ZWS_CREDITO")]
    public interface ZWS_CREDITO {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación ZfmWsCredito no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:soap:functions:mc-style:ZWS_CREDITO:ZfmWsCreditoRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ESIDIFCredito.service.ZfmWsCreditoResponse1 ZfmWsCredito(ESIDIFCredito.service.ZfmWsCreditoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:soap:functions:mc-style:ZWS_CREDITO:ZfmWsCreditoRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<ESIDIFCredito.service.ZfmWsCreditoResponse1> ZfmWsCreditoAsync(ESIDIFCredito.service.ZfmWsCreditoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZfmWsCredito : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZdsCreditoCabecera iCabeceraField;
        
        private string iCuilUserField;
        
        private string iIpUserField;
        
        private ZdsEntradasCredito[] itEntradaCreditoField;
        
        private ZdsEntradasRecurso[] itEntradaRecursoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ZdsCreditoCabecera ICabecera {
            get {
                return this.iCabeceraField;
            }
            set {
                this.iCabeceraField = value;
                this.RaisePropertyChanged("ICabecera");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ICuilUser {
            get {
                return this.iCuilUserField;
            }
            set {
                this.iCuilUserField = value;
                this.RaisePropertyChanged("ICuilUser");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string IIpUser {
            get {
                return this.iIpUserField;
            }
            set {
                this.iIpUserField = value;
                this.RaisePropertyChanged("IIpUser");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZdsEntradasCredito[] ItEntradaCredito {
            get {
                return this.itEntradaCreditoField;
            }
            set {
                this.itEntradaCreditoField = value;
                this.RaisePropertyChanged("ItEntradaCredito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZdsEntradasRecurso[] ItEntradaRecurso {
            get {
                return this.itEntradaRecursoField;
            }
            set {
                this.itEntradaRecursoField = value;
                this.RaisePropertyChanged("ItEntradaRecurso");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZdsCreditoCabecera : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fechaenvioField;
        
        private string tipocomprobanteField;
        
        private string ejercicioField;
        
        private string numerocomprobanteField;
        
        private string entidademisoraField;
        
        private string entidadprocesoField;
        
        private string estadoField;
        
        private string fechaaplicacionField;
        
        private string ejercicioactoadmField;
        
        private string numeroactoadmField;
        
        private string tipoactoadmField;
        
        private string fechaactoadmField;
        
        private string codigoconceptoField;
        
        private string descripcionconceptoField;
        
        private string identificaciontramiteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Fechaenvio {
            get {
                return this.fechaenvioField;
            }
            set {
                this.fechaenvioField = value;
                this.RaisePropertyChanged("Fechaenvio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Tipocomprobante {
            get {
                return this.tipocomprobanteField;
            }
            set {
                this.tipocomprobanteField = value;
                this.RaisePropertyChanged("Tipocomprobante");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Ejercicio {
            get {
                return this.ejercicioField;
            }
            set {
                this.ejercicioField = value;
                this.RaisePropertyChanged("Ejercicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Numerocomprobante {
            get {
                return this.numerocomprobanteField;
            }
            set {
                this.numerocomprobanteField = value;
                this.RaisePropertyChanged("Numerocomprobante");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Entidademisora {
            get {
                return this.entidademisoraField;
            }
            set {
                this.entidademisoraField = value;
                this.RaisePropertyChanged("Entidademisora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Entidadproceso {
            get {
                return this.entidadprocesoField;
            }
            set {
                this.entidadprocesoField = value;
                this.RaisePropertyChanged("Entidadproceso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("Estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Fechaaplicacion {
            get {
                return this.fechaaplicacionField;
            }
            set {
                this.fechaaplicacionField = value;
                this.RaisePropertyChanged("Fechaaplicacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string Ejercicioactoadm {
            get {
                return this.ejercicioactoadmField;
            }
            set {
                this.ejercicioactoadmField = value;
                this.RaisePropertyChanged("Ejercicioactoadm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string Numeroactoadm {
            get {
                return this.numeroactoadmField;
            }
            set {
                this.numeroactoadmField = value;
                this.RaisePropertyChanged("Numeroactoadm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string Tipoactoadm {
            get {
                return this.tipoactoadmField;
            }
            set {
                this.tipoactoadmField = value;
                this.RaisePropertyChanged("Tipoactoadm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string Fechaactoadm {
            get {
                return this.fechaactoadmField;
            }
            set {
                this.fechaactoadmField = value;
                this.RaisePropertyChanged("Fechaactoadm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string Codigoconcepto {
            get {
                return this.codigoconceptoField;
            }
            set {
                this.codigoconceptoField = value;
                this.RaisePropertyChanged("Codigoconcepto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string Descripcionconcepto {
            get {
                return this.descripcionconceptoField;
            }
            set {
                this.descripcionconceptoField = value;
                this.RaisePropertyChanged("Descripcionconcepto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string Identificaciontramite {
            get {
                return this.identificaciontramiteField;
            }
            set {
                this.identificaciontramiteField = value;
                this.RaisePropertyChanged("Identificaciontramite");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZdsWsPresupOutput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZdsEntradasRecurso : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sectorField;
        
        private string subsectorField;
        
        private string caracterField;
        
        private string jurisdiccionField;
        
        private string subjurisdiccionField;
        
        private string entidadField;
        
        private string safField;
        
        private string tipoField;
        
        private string claseField;
        
        private string conceptoField;
        
        private string subconceptoField;
        
        private string procedenciaField;
        
        private string fuenteField;
        
        private string monedaField;
        
        private string entidadorigendestinoField;
        
        private string prestamoexternoField;
        
        private string clasificadoreconomicorecursoField;
        
        private string recursoinicialField;
        
        private string recursovigenteField;
        
        private string recursorestringidoField;
        
        private string importecomprobanterecursoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Sector {
            get {
                return this.sectorField;
            }
            set {
                this.sectorField = value;
                this.RaisePropertyChanged("Sector");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Subsector {
            get {
                return this.subsectorField;
            }
            set {
                this.subsectorField = value;
                this.RaisePropertyChanged("Subsector");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Caracter {
            get {
                return this.caracterField;
            }
            set {
                this.caracterField = value;
                this.RaisePropertyChanged("Caracter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Jurisdiccion {
            get {
                return this.jurisdiccionField;
            }
            set {
                this.jurisdiccionField = value;
                this.RaisePropertyChanged("Jurisdiccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Subjurisdiccion {
            get {
                return this.subjurisdiccionField;
            }
            set {
                this.subjurisdiccionField = value;
                this.RaisePropertyChanged("Subjurisdiccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Entidad {
            get {
                return this.entidadField;
            }
            set {
                this.entidadField = value;
                this.RaisePropertyChanged("Entidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Saf {
            get {
                return this.safField;
            }
            set {
                this.safField = value;
                this.RaisePropertyChanged("Saf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("Tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string Clase {
            get {
                return this.claseField;
            }
            set {
                this.claseField = value;
                this.RaisePropertyChanged("Clase");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string Concepto {
            get {
                return this.conceptoField;
            }
            set {
                this.conceptoField = value;
                this.RaisePropertyChanged("Concepto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string Subconcepto {
            get {
                return this.subconceptoField;
            }
            set {
                this.subconceptoField = value;
                this.RaisePropertyChanged("Subconcepto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string Procedencia {
            get {
                return this.procedenciaField;
            }
            set {
                this.procedenciaField = value;
                this.RaisePropertyChanged("Procedencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string Fuente {
            get {
                return this.fuenteField;
            }
            set {
                this.fuenteField = value;
                this.RaisePropertyChanged("Fuente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string Moneda {
            get {
                return this.monedaField;
            }
            set {
                this.monedaField = value;
                this.RaisePropertyChanged("Moneda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string Entidadorigendestino {
            get {
                return this.entidadorigendestinoField;
            }
            set {
                this.entidadorigendestinoField = value;
                this.RaisePropertyChanged("Entidadorigendestino");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string Prestamoexterno {
            get {
                return this.prestamoexternoField;
            }
            set {
                this.prestamoexternoField = value;
                this.RaisePropertyChanged("Prestamoexterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string Clasificadoreconomicorecurso {
            get {
                return this.clasificadoreconomicorecursoField;
            }
            set {
                this.clasificadoreconomicorecursoField = value;
                this.RaisePropertyChanged("Clasificadoreconomicorecurso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string Recursoinicial {
            get {
                return this.recursoinicialField;
            }
            set {
                this.recursoinicialField = value;
                this.RaisePropertyChanged("Recursoinicial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string Recursovigente {
            get {
                return this.recursovigenteField;
            }
            set {
                this.recursovigenteField = value;
                this.RaisePropertyChanged("Recursovigente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string Recursorestringido {
            get {
                return this.recursorestringidoField;
            }
            set {
                this.recursorestringidoField = value;
                this.RaisePropertyChanged("Recursorestringido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string Importecomprobanterecurso {
            get {
                return this.importecomprobanterecursoField;
            }
            set {
                this.importecomprobanterecursoField = value;
                this.RaisePropertyChanged("Importecomprobanterecurso");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZdsEntradasCredito : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sectorField;
        
        private string subsectorField;
        
        private string caracterField;
        
        private string jurisdiccionField;
        
        private string subjurisdiccionField;
        
        private string entidadField;
        
        private string safField;
        
        private string programaField;
        
        private string subprogramaField;
        
        private string proyectoField;
        
        private string actividadField;
        
        private string obraField;
        
        private string ubicaciongeograficaField;
        
        private string incisoField;
        
        private string principalField;
        
        private string parcialField;
        
        private string subparcialField;
        
        private string procedenciaField;
        
        private string fuenteField;
        
        private string monedaField;
        
        private string entidadorigendestinoField;
        
        private string prestamoexternoField;
        
        private string clasificadoreconomicocreditoField;
        
        private string finalidadField;
        
        private string funcionField;
        
        private string bapinField;
        
        private string creditoinicialField;
        
        private string creditovigenteField;
        
        private string creditorestringidoField;
        
        private string importecomprobantecreditoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Sector {
            get {
                return this.sectorField;
            }
            set {
                this.sectorField = value;
                this.RaisePropertyChanged("Sector");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Subsector {
            get {
                return this.subsectorField;
            }
            set {
                this.subsectorField = value;
                this.RaisePropertyChanged("Subsector");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Caracter {
            get {
                return this.caracterField;
            }
            set {
                this.caracterField = value;
                this.RaisePropertyChanged("Caracter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Jurisdiccion {
            get {
                return this.jurisdiccionField;
            }
            set {
                this.jurisdiccionField = value;
                this.RaisePropertyChanged("Jurisdiccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Subjurisdiccion {
            get {
                return this.subjurisdiccionField;
            }
            set {
                this.subjurisdiccionField = value;
                this.RaisePropertyChanged("Subjurisdiccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Entidad {
            get {
                return this.entidadField;
            }
            set {
                this.entidadField = value;
                this.RaisePropertyChanged("Entidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Saf {
            get {
                return this.safField;
            }
            set {
                this.safField = value;
                this.RaisePropertyChanged("Saf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Programa {
            get {
                return this.programaField;
            }
            set {
                this.programaField = value;
                this.RaisePropertyChanged("Programa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string Subprograma {
            get {
                return this.subprogramaField;
            }
            set {
                this.subprogramaField = value;
                this.RaisePropertyChanged("Subprograma");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string Proyecto {
            get {
                return this.proyectoField;
            }
            set {
                this.proyectoField = value;
                this.RaisePropertyChanged("Proyecto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string Actividad {
            get {
                return this.actividadField;
            }
            set {
                this.actividadField = value;
                this.RaisePropertyChanged("Actividad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string Obra {
            get {
                return this.obraField;
            }
            set {
                this.obraField = value;
                this.RaisePropertyChanged("Obra");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string Ubicaciongeografica {
            get {
                return this.ubicaciongeograficaField;
            }
            set {
                this.ubicaciongeograficaField = value;
                this.RaisePropertyChanged("Ubicaciongeografica");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string Inciso {
            get {
                return this.incisoField;
            }
            set {
                this.incisoField = value;
                this.RaisePropertyChanged("Inciso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string Principal {
            get {
                return this.principalField;
            }
            set {
                this.principalField = value;
                this.RaisePropertyChanged("Principal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string Parcial {
            get {
                return this.parcialField;
            }
            set {
                this.parcialField = value;
                this.RaisePropertyChanged("Parcial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string Subparcial {
            get {
                return this.subparcialField;
            }
            set {
                this.subparcialField = value;
                this.RaisePropertyChanged("Subparcial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string Procedencia {
            get {
                return this.procedenciaField;
            }
            set {
                this.procedenciaField = value;
                this.RaisePropertyChanged("Procedencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string Fuente {
            get {
                return this.fuenteField;
            }
            set {
                this.fuenteField = value;
                this.RaisePropertyChanged("Fuente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string Moneda {
            get {
                return this.monedaField;
            }
            set {
                this.monedaField = value;
                this.RaisePropertyChanged("Moneda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string Entidadorigendestino {
            get {
                return this.entidadorigendestinoField;
            }
            set {
                this.entidadorigendestinoField = value;
                this.RaisePropertyChanged("Entidadorigendestino");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string Prestamoexterno {
            get {
                return this.prestamoexternoField;
            }
            set {
                this.prestamoexternoField = value;
                this.RaisePropertyChanged("Prestamoexterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string Clasificadoreconomicocredito {
            get {
                return this.clasificadoreconomicocreditoField;
            }
            set {
                this.clasificadoreconomicocreditoField = value;
                this.RaisePropertyChanged("Clasificadoreconomicocredito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string Finalidad {
            get {
                return this.finalidadField;
            }
            set {
                this.finalidadField = value;
                this.RaisePropertyChanged("Finalidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string Funcion {
            get {
                return this.funcionField;
            }
            set {
                this.funcionField = value;
                this.RaisePropertyChanged("Funcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string Bapin {
            get {
                return this.bapinField;
            }
            set {
                this.bapinField = value;
                this.RaisePropertyChanged("Bapin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string Creditoinicial {
            get {
                return this.creditoinicialField;
            }
            set {
                this.creditoinicialField = value;
                this.RaisePropertyChanged("Creditoinicial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string Creditovigente {
            get {
                return this.creditovigenteField;
            }
            set {
                this.creditovigenteField = value;
                this.RaisePropertyChanged("Creditovigente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string Creditorestringido {
            get {
                return this.creditorestringidoField;
            }
            set {
                this.creditorestringidoField = value;
                this.RaisePropertyChanged("Creditorestringido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string Importecomprobantecredito {
            get {
                return this.importecomprobantecreditoField;
            }
            set {
                this.importecomprobantecreditoField = value;
                this.RaisePropertyChanged("Importecomprobantecredito");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZfmWsCreditoResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZdsWsPresupOutput eOutputField;
        
        private ZdsEntradasCredito[] itEntradaCreditoField;
        
        private ZdsEntradasRecurso[] itEntradaRecursoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ZdsWsPresupOutput EOutput {
            get {
                return this.eOutputField;
            }
            set {
                this.eOutputField = value;
                this.RaisePropertyChanged("EOutput");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZdsEntradasCredito[] ItEntradaCredito {
            get {
                return this.itEntradaCreditoField;
            }
            set {
                this.itEntradaCreditoField = value;
                this.RaisePropertyChanged("ItEntradaCredito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZdsEntradasRecurso[] ItEntradaRecurso {
            get {
                return this.itEntradaRecursoField;
            }
            set {
                this.itEntradaRecursoField = value;
                this.RaisePropertyChanged("ItEntradaRecurso");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZfmWsCreditoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public ESIDIFCredito.service.ZfmWsCredito ZfmWsCredito;
        
        public ZfmWsCreditoRequest() {
        }
        
        public ZfmWsCreditoRequest(ESIDIFCredito.service.ZfmWsCredito ZfmWsCredito) {
            this.ZfmWsCredito = ZfmWsCredito;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZfmWsCreditoResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public ESIDIFCredito.service.ZfmWsCreditoResponse ZfmWsCreditoResponse;
        
        public ZfmWsCreditoResponse1() {
        }
        
        public ZfmWsCreditoResponse1(ESIDIFCredito.service.ZfmWsCreditoResponse ZfmWsCreditoResponse) {
            this.ZfmWsCreditoResponse = ZfmWsCreditoResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZWS_CREDITOChannel : ESIDIFCredito.service.ZWS_CREDITO, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZWS_CREDITOClient : System.ServiceModel.ClientBase<ESIDIFCredito.service.ZWS_CREDITO>, ESIDIFCredito.service.ZWS_CREDITO {
        
        public ZWS_CREDITOClient() {
        }
        
        public ZWS_CREDITOClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZWS_CREDITOClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_CREDITOClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_CREDITOClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ESIDIFCredito.service.ZfmWsCreditoResponse1 ESIDIFCredito.service.ZWS_CREDITO.ZfmWsCredito(ESIDIFCredito.service.ZfmWsCreditoRequest request) {
            return base.Channel.ZfmWsCredito(request);
        }
        
        public ESIDIFCredito.service.ZfmWsCreditoResponse ZfmWsCredito(ESIDIFCredito.service.ZfmWsCredito ZfmWsCredito1) {
            ESIDIFCredito.service.ZfmWsCreditoRequest inValue = new ESIDIFCredito.service.ZfmWsCreditoRequest();
            inValue.ZfmWsCredito = ZfmWsCredito1;
            ESIDIFCredito.service.ZfmWsCreditoResponse1 retVal = ((ESIDIFCredito.service.ZWS_CREDITO)(this)).ZfmWsCredito(inValue);
            return retVal.ZfmWsCreditoResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ESIDIFCredito.service.ZfmWsCreditoResponse1> ESIDIFCredito.service.ZWS_CREDITO.ZfmWsCreditoAsync(ESIDIFCredito.service.ZfmWsCreditoRequest request) {
            return base.Channel.ZfmWsCreditoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ESIDIFCredito.service.ZfmWsCreditoResponse1> ZfmWsCreditoAsync(ESIDIFCredito.service.ZfmWsCredito ZfmWsCredito) {
            ESIDIFCredito.service.ZfmWsCreditoRequest inValue = new ESIDIFCredito.service.ZfmWsCreditoRequest();
            inValue.ZfmWsCredito = ZfmWsCredito;
            return ((ESIDIFCredito.service.ZWS_CREDITO)(this)).ZfmWsCreditoAsync(inValue);
        }
    }
}
