//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESIDIFCommon.GestionService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://anses.gov.ar", ConfigurationName="GestionService.GestionServiceSoap")]
    public interface GestionServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento User del espacio de nombres http://anses.gov.ar no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="/ConsultarKey", ReplyAction="*")]
        ESIDIFCommon.GestionService.ConsultarKeyResponse ConsultarKey(ESIDIFCommon.GestionService.ConsultarKeyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="/ConsultarKey", ReplyAction="*")]
        System.Threading.Tasks.Task<ESIDIFCommon.GestionService.ConsultarKeyResponse> ConsultarKeyAsync(ESIDIFCommon.GestionService.ConsultarKeyRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarKeyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarKey", Namespace="http://anses.gov.ar", Order=0)]
        public ESIDIFCommon.GestionService.ConsultarKeyRequestBody Body;
        
        public ConsultarKeyRequest() {
        }
        
        public ConsultarKeyRequest(ESIDIFCommon.GestionService.ConsultarKeyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://anses.gov.ar")]
    public partial class ConsultarKeyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string User;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Mark;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Value;
        
        public ConsultarKeyRequestBody() {
        }
        
        public ConsultarKeyRequestBody(string User, string Mark, string Value) {
            this.User = User;
            this.Mark = Mark;
            this.Value = Value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarKeyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarKeyResponse", Namespace="http://anses.gov.ar", Order=0)]
        public ESIDIFCommon.GestionService.ConsultarKeyResponseBody Body;
        
        public ConsultarKeyResponse() {
        }
        
        public ConsultarKeyResponse(ESIDIFCommon.GestionService.ConsultarKeyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://anses.gov.ar")]
    public partial class ConsultarKeyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConsultarKeyResult;
        
        public ConsultarKeyResponseBody() {
        }
        
        public ConsultarKeyResponseBody(string ConsultarKeyResult) {
            this.ConsultarKeyResult = ConsultarKeyResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GestionServiceSoapChannel : ESIDIFCommon.GestionService.GestionServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GestionServiceSoapClient : System.ServiceModel.ClientBase<ESIDIFCommon.GestionService.GestionServiceSoap>, ESIDIFCommon.GestionService.GestionServiceSoap {
        
        public GestionServiceSoapClient() {
        }
        
        public GestionServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GestionServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ESIDIFCommon.GestionService.ConsultarKeyResponse ESIDIFCommon.GestionService.GestionServiceSoap.ConsultarKey(ESIDIFCommon.GestionService.ConsultarKeyRequest request) {
            return base.Channel.ConsultarKey(request);
        }
        
        public string ConsultarKey(string User, string Mark, string Value) {
            ESIDIFCommon.GestionService.ConsultarKeyRequest inValue = new ESIDIFCommon.GestionService.ConsultarKeyRequest();
            inValue.Body = new ESIDIFCommon.GestionService.ConsultarKeyRequestBody();
            inValue.Body.User = User;
            inValue.Body.Mark = Mark;
            inValue.Body.Value = Value;
            ESIDIFCommon.GestionService.ConsultarKeyResponse retVal = ((ESIDIFCommon.GestionService.GestionServiceSoap)(this)).ConsultarKey(inValue);
            return retVal.Body.ConsultarKeyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ESIDIFCommon.GestionService.ConsultarKeyResponse> ESIDIFCommon.GestionService.GestionServiceSoap.ConsultarKeyAsync(ESIDIFCommon.GestionService.ConsultarKeyRequest request) {
            return base.Channel.ConsultarKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<ESIDIFCommon.GestionService.ConsultarKeyResponse> ConsultarKeyAsync(string User, string Mark, string Value) {
            ESIDIFCommon.GestionService.ConsultarKeyRequest inValue = new ESIDIFCommon.GestionService.ConsultarKeyRequest();
            inValue.Body = new ESIDIFCommon.GestionService.ConsultarKeyRequestBody();
            inValue.Body.User = User;
            inValue.Body.Mark = Mark;
            inValue.Body.Value = Value;
            return ((ESIDIFCommon.GestionService.GestionServiceSoap)(this)).ConsultarKeyAsync(inValue);
        }
    }
}
