//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESIDIFCuota.service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", ConfigurationName="service.ZWS_CUOTA")]
    public interface ZWS_CUOTA {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación ZfmWsCuota no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:soap:functions:mc-style:ZWS_CUOTA:ZfmWsCuotaRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ESIDIFCuota.service.ZfmWsCuotaResponse1 ZfmWsCuota(ESIDIFCuota.service.ZfmWsCuotaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:soap:functions:mc-style:ZWS_CUOTA:ZfmWsCuotaRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<ESIDIFCuota.service.ZfmWsCuotaResponse1> ZfmWsCuotaAsync(ESIDIFCuota.service.ZfmWsCuotaRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZfmWsCuota : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZdsCuotaCabecera iCabeceraField;
        
        private string iCuilUserField;
        
        private string iIpUserField;
        
        private ZdsEntradasCuota[] itEntradaCuotaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ZdsCuotaCabecera ICabecera {
            get {
                return this.iCabeceraField;
            }
            set {
                this.iCabeceraField = value;
                this.RaisePropertyChanged("ICabecera");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ICuilUser {
            get {
                return this.iCuilUserField;
            }
            set {
                this.iCuilUserField = value;
                this.RaisePropertyChanged("ICuilUser");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string IIpUser {
            get {
                return this.iIpUserField;
            }
            set {
                this.iIpUserField = value;
                this.RaisePropertyChanged("IIpUser");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZdsEntradasCuota[] ItEntradaCuota {
            get {
                return this.itEntradaCuotaField;
            }
            set {
                this.itEntradaCuotaField = value;
                this.RaisePropertyChanged("ItEntradaCuota");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZdsCuotaCabecera : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fechaenvioField;
        
        private string tipocomprobanteField;
        
        private string ejercicioField;
        
        private string numerocomprobanteField;
        
        private string periodoField;
        
        private string entidademisoraField;
        
        private string entidadprocesoField;
        
        private string estadoField;
        
        private string fechaaplicacionField;
        
        private string ejercicioactoadmField;
        
        private string numeroactoadmField;
        
        private string tipoactoadmField;
        
        private string fechaactoadmField;
        
        private string codigoconceptoField;
        
        private string descripcionconceptoField;
        
        private string identificaciontramiteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Fechaenvio {
            get {
                return this.fechaenvioField;
            }
            set {
                this.fechaenvioField = value;
                this.RaisePropertyChanged("Fechaenvio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Tipocomprobante {
            get {
                return this.tipocomprobanteField;
            }
            set {
                this.tipocomprobanteField = value;
                this.RaisePropertyChanged("Tipocomprobante");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Ejercicio {
            get {
                return this.ejercicioField;
            }
            set {
                this.ejercicioField = value;
                this.RaisePropertyChanged("Ejercicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Numerocomprobante {
            get {
                return this.numerocomprobanteField;
            }
            set {
                this.numerocomprobanteField = value;
                this.RaisePropertyChanged("Numerocomprobante");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Periodo {
            get {
                return this.periodoField;
            }
            set {
                this.periodoField = value;
                this.RaisePropertyChanged("Periodo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Entidademisora {
            get {
                return this.entidademisoraField;
            }
            set {
                this.entidademisoraField = value;
                this.RaisePropertyChanged("Entidademisora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Entidadproceso {
            get {
                return this.entidadprocesoField;
            }
            set {
                this.entidadprocesoField = value;
                this.RaisePropertyChanged("Entidadproceso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("Estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string Fechaaplicacion {
            get {
                return this.fechaaplicacionField;
            }
            set {
                this.fechaaplicacionField = value;
                this.RaisePropertyChanged("Fechaaplicacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string Ejercicioactoadm {
            get {
                return this.ejercicioactoadmField;
            }
            set {
                this.ejercicioactoadmField = value;
                this.RaisePropertyChanged("Ejercicioactoadm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string Numeroactoadm {
            get {
                return this.numeroactoadmField;
            }
            set {
                this.numeroactoadmField = value;
                this.RaisePropertyChanged("Numeroactoadm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string Tipoactoadm {
            get {
                return this.tipoactoadmField;
            }
            set {
                this.tipoactoadmField = value;
                this.RaisePropertyChanged("Tipoactoadm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string Fechaactoadm {
            get {
                return this.fechaactoadmField;
            }
            set {
                this.fechaactoadmField = value;
                this.RaisePropertyChanged("Fechaactoadm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string Codigoconcepto {
            get {
                return this.codigoconceptoField;
            }
            set {
                this.codigoconceptoField = value;
                this.RaisePropertyChanged("Codigoconcepto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string Descripcionconcepto {
            get {
                return this.descripcionconceptoField;
            }
            set {
                this.descripcionconceptoField = value;
                this.RaisePropertyChanged("Descripcionconcepto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string Identificaciontramite {
            get {
                return this.identificaciontramiteField;
            }
            set {
                this.identificaciontramiteField = value;
                this.RaisePropertyChanged("Identificaciontramite");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZdsWsPresupOutput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZdsEntradasCuota : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sectorField;
        
        private string subsectorField;
        
        private string caracterField;
        
        private string jurisdiccionField;
        
        private string subjurisdiccionField;
        
        private string entidadField;
        
        private string safField;
        
        private string programaField;
        
        private string subprogramaField;
        
        private string proyectoField;
        
        private string actividadField;
        
        private string obraField;
        
        private string incisoField;
        
        private string principalField;
        
        private string parcialField;
        
        private string subparcialField;
        
        private string procedenciaField;
        
        private string fuenteField;
        
        private string compromisoinicialField;
        
        private string compromisovigenteField;
        
        private string compromisorestringidoField;
        
        private string devengadoinicial1Field;
        
        private string devengadovigente1Field;
        
        private string devengadorestringido1Field;
        
        private string devengadoinicial2Field;
        
        private string devengadovigente2Field;
        
        private string devengadorestringido2Field;
        
        private string devengadoinicial3Field;
        
        private string devengadovigente3Field;
        
        private string devengadorestringido3Field;
        
        private string compromisocomprobanteField;
        
        private string devengado1comprobanteField;
        
        private string devengado2comprobanteField;
        
        private string devengado3comprobanteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Sector {
            get {
                return this.sectorField;
            }
            set {
                this.sectorField = value;
                this.RaisePropertyChanged("Sector");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Subsector {
            get {
                return this.subsectorField;
            }
            set {
                this.subsectorField = value;
                this.RaisePropertyChanged("Subsector");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Caracter {
            get {
                return this.caracterField;
            }
            set {
                this.caracterField = value;
                this.RaisePropertyChanged("Caracter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Jurisdiccion {
            get {
                return this.jurisdiccionField;
            }
            set {
                this.jurisdiccionField = value;
                this.RaisePropertyChanged("Jurisdiccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Subjurisdiccion {
            get {
                return this.subjurisdiccionField;
            }
            set {
                this.subjurisdiccionField = value;
                this.RaisePropertyChanged("Subjurisdiccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Entidad {
            get {
                return this.entidadField;
            }
            set {
                this.entidadField = value;
                this.RaisePropertyChanged("Entidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Saf {
            get {
                return this.safField;
            }
            set {
                this.safField = value;
                this.RaisePropertyChanged("Saf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Programa {
            get {
                return this.programaField;
            }
            set {
                this.programaField = value;
                this.RaisePropertyChanged("Programa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string Subprograma {
            get {
                return this.subprogramaField;
            }
            set {
                this.subprogramaField = value;
                this.RaisePropertyChanged("Subprograma");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string Proyecto {
            get {
                return this.proyectoField;
            }
            set {
                this.proyectoField = value;
                this.RaisePropertyChanged("Proyecto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string Actividad {
            get {
                return this.actividadField;
            }
            set {
                this.actividadField = value;
                this.RaisePropertyChanged("Actividad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string Obra {
            get {
                return this.obraField;
            }
            set {
                this.obraField = value;
                this.RaisePropertyChanged("Obra");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string Inciso {
            get {
                return this.incisoField;
            }
            set {
                this.incisoField = value;
                this.RaisePropertyChanged("Inciso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string Principal {
            get {
                return this.principalField;
            }
            set {
                this.principalField = value;
                this.RaisePropertyChanged("Principal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string Parcial {
            get {
                return this.parcialField;
            }
            set {
                this.parcialField = value;
                this.RaisePropertyChanged("Parcial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string Subparcial {
            get {
                return this.subparcialField;
            }
            set {
                this.subparcialField = value;
                this.RaisePropertyChanged("Subparcial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string Procedencia {
            get {
                return this.procedenciaField;
            }
            set {
                this.procedenciaField = value;
                this.RaisePropertyChanged("Procedencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string Fuente {
            get {
                return this.fuenteField;
            }
            set {
                this.fuenteField = value;
                this.RaisePropertyChanged("Fuente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string Compromisoinicial {
            get {
                return this.compromisoinicialField;
            }
            set {
                this.compromisoinicialField = value;
                this.RaisePropertyChanged("Compromisoinicial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string Compromisovigente {
            get {
                return this.compromisovigenteField;
            }
            set {
                this.compromisovigenteField = value;
                this.RaisePropertyChanged("Compromisovigente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string Compromisorestringido {
            get {
                return this.compromisorestringidoField;
            }
            set {
                this.compromisorestringidoField = value;
                this.RaisePropertyChanged("Compromisorestringido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string Devengadoinicial1 {
            get {
                return this.devengadoinicial1Field;
            }
            set {
                this.devengadoinicial1Field = value;
                this.RaisePropertyChanged("Devengadoinicial1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string Devengadovigente1 {
            get {
                return this.devengadovigente1Field;
            }
            set {
                this.devengadovigente1Field = value;
                this.RaisePropertyChanged("Devengadovigente1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string Devengadorestringido1 {
            get {
                return this.devengadorestringido1Field;
            }
            set {
                this.devengadorestringido1Field = value;
                this.RaisePropertyChanged("Devengadorestringido1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string Devengadoinicial2 {
            get {
                return this.devengadoinicial2Field;
            }
            set {
                this.devengadoinicial2Field = value;
                this.RaisePropertyChanged("Devengadoinicial2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string Devengadovigente2 {
            get {
                return this.devengadovigente2Field;
            }
            set {
                this.devengadovigente2Field = value;
                this.RaisePropertyChanged("Devengadovigente2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string Devengadorestringido2 {
            get {
                return this.devengadorestringido2Field;
            }
            set {
                this.devengadorestringido2Field = value;
                this.RaisePropertyChanged("Devengadorestringido2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string Devengadoinicial3 {
            get {
                return this.devengadoinicial3Field;
            }
            set {
                this.devengadoinicial3Field = value;
                this.RaisePropertyChanged("Devengadoinicial3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string Devengadovigente3 {
            get {
                return this.devengadovigente3Field;
            }
            set {
                this.devengadovigente3Field = value;
                this.RaisePropertyChanged("Devengadovigente3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string Devengadorestringido3 {
            get {
                return this.devengadorestringido3Field;
            }
            set {
                this.devengadorestringido3Field = value;
                this.RaisePropertyChanged("Devengadorestringido3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string Compromisocomprobante {
            get {
                return this.compromisocomprobanteField;
            }
            set {
                this.compromisocomprobanteField = value;
                this.RaisePropertyChanged("Compromisocomprobante");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public string Devengado1comprobante {
            get {
                return this.devengado1comprobanteField;
            }
            set {
                this.devengado1comprobanteField = value;
                this.RaisePropertyChanged("Devengado1comprobante");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public string Devengado2comprobante {
            get {
                return this.devengado2comprobanteField;
            }
            set {
                this.devengado2comprobanteField = value;
                this.RaisePropertyChanged("Devengado2comprobante");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public string Devengado3comprobante {
            get {
                return this.devengado3comprobanteField;
            }
            set {
                this.devengado3comprobanteField = value;
                this.RaisePropertyChanged("Devengado3comprobante");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZfmWsCuotaResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZdsWsPresupOutput eOutputField;
        
        private ZdsEntradasCuota[] itEntradaCuotaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ZdsWsPresupOutput EOutput {
            get {
                return this.eOutputField;
            }
            set {
                this.eOutputField = value;
                this.RaisePropertyChanged("EOutput");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZdsEntradasCuota[] ItEntradaCuota {
            get {
                return this.itEntradaCuotaField;
            }
            set {
                this.itEntradaCuotaField = value;
                this.RaisePropertyChanged("ItEntradaCuota");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZfmWsCuotaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public ESIDIFCuota.service.ZfmWsCuota ZfmWsCuota;
        
        public ZfmWsCuotaRequest() {
        }
        
        public ZfmWsCuotaRequest(ESIDIFCuota.service.ZfmWsCuota ZfmWsCuota) {
            this.ZfmWsCuota = ZfmWsCuota;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZfmWsCuotaResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public ESIDIFCuota.service.ZfmWsCuotaResponse ZfmWsCuotaResponse;
        
        public ZfmWsCuotaResponse1() {
        }
        
        public ZfmWsCuotaResponse1(ESIDIFCuota.service.ZfmWsCuotaResponse ZfmWsCuotaResponse) {
            this.ZfmWsCuotaResponse = ZfmWsCuotaResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZWS_CUOTAChannel : ESIDIFCuota.service.ZWS_CUOTA, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZWS_CUOTAClient : System.ServiceModel.ClientBase<ESIDIFCuota.service.ZWS_CUOTA>, ESIDIFCuota.service.ZWS_CUOTA {
        
        public ZWS_CUOTAClient() {
        }
        
        public ZWS_CUOTAClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZWS_CUOTAClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_CUOTAClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_CUOTAClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ESIDIFCuota.service.ZfmWsCuotaResponse1 ESIDIFCuota.service.ZWS_CUOTA.ZfmWsCuota(ESIDIFCuota.service.ZfmWsCuotaRequest request) {
            return base.Channel.ZfmWsCuota(request);
        }
        
        public ESIDIFCuota.service.ZfmWsCuotaResponse ZfmWsCuota(ESIDIFCuota.service.ZfmWsCuota ZfmWsCuota1) {
            ESIDIFCuota.service.ZfmWsCuotaRequest inValue = new ESIDIFCuota.service.ZfmWsCuotaRequest();
            inValue.ZfmWsCuota = ZfmWsCuota1;
            ESIDIFCuota.service.ZfmWsCuotaResponse1 retVal = ((ESIDIFCuota.service.ZWS_CUOTA)(this)).ZfmWsCuota(inValue);
            return retVal.ZfmWsCuotaResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ESIDIFCuota.service.ZfmWsCuotaResponse1> ESIDIFCuota.service.ZWS_CUOTA.ZfmWsCuotaAsync(ESIDIFCuota.service.ZfmWsCuotaRequest request) {
            return base.Channel.ZfmWsCuotaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ESIDIFCuota.service.ZfmWsCuotaResponse1> ZfmWsCuotaAsync(ESIDIFCuota.service.ZfmWsCuota ZfmWsCuota) {
            ESIDIFCuota.service.ZfmWsCuotaRequest inValue = new ESIDIFCuota.service.ZfmWsCuotaRequest();
            inValue.ZfmWsCuota = ZfmWsCuota;
            return ((ESIDIFCuota.service.ZWS_CUOTA)(this)).ZfmWsCuotaAsync(inValue);
        }
    }
}
