//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESIDIFRecursos.service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.webService.server.recursos.esidif.mecon.gov.ar", ConfigurationName="service.generarComprobanteRecursosService")]
    public interface generarComprobanteRecursosService {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación generarComprobanteRecursos no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="https://ws-si.mecon.gov.ar/ws/recursos/generarComprobanteRecursosService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(itemRecursosBean))]
        ESIDIFRecursos.service.generarComprobanteRecursosResponse generarComprobanteRecursos(ESIDIFRecursos.service.generarComprobanteRecursosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ws-si.mecon.gov.ar/ws/recursos/generarComprobanteRecursosService", ReplyAction="*")]
        System.Threading.Tasks.Task<ESIDIFRecursos.service.generarComprobanteRecursosResponse> generarComprobanteRecursosAsync(ESIDIFRecursos.service.generarComprobanteRecursosRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bean.webService.common.recursos.esidif.mecon.gov.ar")]
    public partial class comprobanteRecursosBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private emisorBean entidadEmisoraField;
        
        private long numeroComprobanteField;
        
        private bool numeroComprobanteFieldSpecified;
        
        private System.DateTime fechaRegistroField;
        
        private bool fechaRegistroFieldSpecified;
        
        private long ejercicioNovedadField;
        
        private bool ejercicioNovedadFieldSpecified;
        
        private long numeroNovedadField;
        
        private bool numeroNovedadFieldSpecified;
        
        private System.DateTime fechaNovedadField;
        
        private bool fechaNovedadFieldSpecified;
        
        private long ejercicioField;
        
        private bool ejercicioFieldSpecified;
        
        private string tipoComprobanteField;
        
        private string tipoRegistroField;
        
        private string etapaField;
        
        private long safField;
        
        private bool safFieldSpecified;
        
        private string gestionField;
        
        private donacionBean donacionField;
        
        private System.DateTime fechaComprobanteField;
        
        private bool fechaComprobanteFieldSpecified;
        
        private long clienteField;
        
        private bool clienteFieldSpecified;
        
        private string medioPercepcionField;
        
        private cuentaOperativaBean cuentaRecaudadoraBancariaField;
        
        private cuentaOperativaBean cuentaRecaudadoraEscrituralField;
        
        private long numeroComprobanteBancarioField;
        
        private bool numeroComprobanteBancarioFieldSpecified;
        
        private cotizacionBean cotizacionField;
        
        private documentoRespaldatorioBean documentoRespaldatorioField;
        
        private identificacionDeTramiteBean identificadorTramiteField;
        
        private string observacionesField;
        
        private bool esInicioVinculoField;
        
        private bool esInicioVinculoFieldSpecified;
        
        private comprobanteOperacionVinculadaBean comprobanteVinculoField;
        
        private comprobanteEjecucionBean comprobanteOrigenField;
        
        private decimal totalMOField;
        
        private bool totalMOFieldSpecified;
        
        private decimal totalMCLField;
        
        private bool totalMCLFieldSpecified;
        
        private itemPresupuestarioRecursosBean[] itemsPresupuestariosField;
        
        private itemNoPresupuestarioRecursosBean[] itemsNoPresupuestariosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public emisorBean entidadEmisora {
            get {
                return this.entidadEmisoraField;
            }
            set {
                this.entidadEmisoraField = value;
                this.RaisePropertyChanged("entidadEmisora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long numeroComprobante {
            get {
                return this.numeroComprobanteField;
            }
            set {
                this.numeroComprobanteField = value;
                this.RaisePropertyChanged("numeroComprobante");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroComprobanteSpecified {
            get {
                return this.numeroComprobanteFieldSpecified;
            }
            set {
                this.numeroComprobanteFieldSpecified = value;
                this.RaisePropertyChanged("numeroComprobanteSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaRegistro {
            get {
                return this.fechaRegistroField;
            }
            set {
                this.fechaRegistroField = value;
                this.RaisePropertyChanged("fechaRegistro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaRegistroSpecified {
            get {
                return this.fechaRegistroFieldSpecified;
            }
            set {
                this.fechaRegistroFieldSpecified = value;
                this.RaisePropertyChanged("fechaRegistroSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public long ejercicioNovedad {
            get {
                return this.ejercicioNovedadField;
            }
            set {
                this.ejercicioNovedadField = value;
                this.RaisePropertyChanged("ejercicioNovedad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ejercicioNovedadSpecified {
            get {
                return this.ejercicioNovedadFieldSpecified;
            }
            set {
                this.ejercicioNovedadFieldSpecified = value;
                this.RaisePropertyChanged("ejercicioNovedadSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public long numeroNovedad {
            get {
                return this.numeroNovedadField;
            }
            set {
                this.numeroNovedadField = value;
                this.RaisePropertyChanged("numeroNovedad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroNovedadSpecified {
            get {
                return this.numeroNovedadFieldSpecified;
            }
            set {
                this.numeroNovedadFieldSpecified = value;
                this.RaisePropertyChanged("numeroNovedadSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime fechaNovedad {
            get {
                return this.fechaNovedadField;
            }
            set {
                this.fechaNovedadField = value;
                this.RaisePropertyChanged("fechaNovedad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaNovedadSpecified {
            get {
                return this.fechaNovedadFieldSpecified;
            }
            set {
                this.fechaNovedadFieldSpecified = value;
                this.RaisePropertyChanged("fechaNovedadSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public long ejercicio {
            get {
                return this.ejercicioField;
            }
            set {
                this.ejercicioField = value;
                this.RaisePropertyChanged("ejercicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ejercicioSpecified {
            get {
                return this.ejercicioFieldSpecified;
            }
            set {
                this.ejercicioFieldSpecified = value;
                this.RaisePropertyChanged("ejercicioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string tipoComprobante {
            get {
                return this.tipoComprobanteField;
            }
            set {
                this.tipoComprobanteField = value;
                this.RaisePropertyChanged("tipoComprobante");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string tipoRegistro {
            get {
                return this.tipoRegistroField;
            }
            set {
                this.tipoRegistroField = value;
                this.RaisePropertyChanged("tipoRegistro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string etapa {
            get {
                return this.etapaField;
            }
            set {
                this.etapaField = value;
                this.RaisePropertyChanged("etapa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public long saf {
            get {
                return this.safField;
            }
            set {
                this.safField = value;
                this.RaisePropertyChanged("saf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool safSpecified {
            get {
                return this.safFieldSpecified;
            }
            set {
                this.safFieldSpecified = value;
                this.RaisePropertyChanged("safSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string gestion {
            get {
                return this.gestionField;
            }
            set {
                this.gestionField = value;
                this.RaisePropertyChanged("gestion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public donacionBean donacion {
            get {
                return this.donacionField;
            }
            set {
                this.donacionField = value;
                this.RaisePropertyChanged("donacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public System.DateTime fechaComprobante {
            get {
                return this.fechaComprobanteField;
            }
            set {
                this.fechaComprobanteField = value;
                this.RaisePropertyChanged("fechaComprobante");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaComprobanteSpecified {
            get {
                return this.fechaComprobanteFieldSpecified;
            }
            set {
                this.fechaComprobanteFieldSpecified = value;
                this.RaisePropertyChanged("fechaComprobanteSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public long cliente {
            get {
                return this.clienteField;
            }
            set {
                this.clienteField = value;
                this.RaisePropertyChanged("cliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool clienteSpecified {
            get {
                return this.clienteFieldSpecified;
            }
            set {
                this.clienteFieldSpecified = value;
                this.RaisePropertyChanged("clienteSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string medioPercepcion {
            get {
                return this.medioPercepcionField;
            }
            set {
                this.medioPercepcionField = value;
                this.RaisePropertyChanged("medioPercepcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public cuentaOperativaBean cuentaRecaudadoraBancaria {
            get {
                return this.cuentaRecaudadoraBancariaField;
            }
            set {
                this.cuentaRecaudadoraBancariaField = value;
                this.RaisePropertyChanged("cuentaRecaudadoraBancaria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public cuentaOperativaBean cuentaRecaudadoraEscritural {
            get {
                return this.cuentaRecaudadoraEscrituralField;
            }
            set {
                this.cuentaRecaudadoraEscrituralField = value;
                this.RaisePropertyChanged("cuentaRecaudadoraEscritural");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public long numeroComprobanteBancario {
            get {
                return this.numeroComprobanteBancarioField;
            }
            set {
                this.numeroComprobanteBancarioField = value;
                this.RaisePropertyChanged("numeroComprobanteBancario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroComprobanteBancarioSpecified {
            get {
                return this.numeroComprobanteBancarioFieldSpecified;
            }
            set {
                this.numeroComprobanteBancarioFieldSpecified = value;
                this.RaisePropertyChanged("numeroComprobanteBancarioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public cotizacionBean cotizacion {
            get {
                return this.cotizacionField;
            }
            set {
                this.cotizacionField = value;
                this.RaisePropertyChanged("cotizacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public documentoRespaldatorioBean documentoRespaldatorio {
            get {
                return this.documentoRespaldatorioField;
            }
            set {
                this.documentoRespaldatorioField = value;
                this.RaisePropertyChanged("documentoRespaldatorio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public identificacionDeTramiteBean identificadorTramite {
            get {
                return this.identificadorTramiteField;
            }
            set {
                this.identificadorTramiteField = value;
                this.RaisePropertyChanged("identificadorTramite");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string observaciones {
            get {
                return this.observacionesField;
            }
            set {
                this.observacionesField = value;
                this.RaisePropertyChanged("observaciones");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public bool esInicioVinculo {
            get {
                return this.esInicioVinculoField;
            }
            set {
                this.esInicioVinculoField = value;
                this.RaisePropertyChanged("esInicioVinculo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool esInicioVinculoSpecified {
            get {
                return this.esInicioVinculoFieldSpecified;
            }
            set {
                this.esInicioVinculoFieldSpecified = value;
                this.RaisePropertyChanged("esInicioVinculoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public comprobanteOperacionVinculadaBean comprobanteVinculo {
            get {
                return this.comprobanteVinculoField;
            }
            set {
                this.comprobanteVinculoField = value;
                this.RaisePropertyChanged("comprobanteVinculo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public comprobanteEjecucionBean comprobanteOrigen {
            get {
                return this.comprobanteOrigenField;
            }
            set {
                this.comprobanteOrigenField = value;
                this.RaisePropertyChanged("comprobanteOrigen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public decimal totalMO {
            get {
                return this.totalMOField;
            }
            set {
                this.totalMOField = value;
                this.RaisePropertyChanged("totalMO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalMOSpecified {
            get {
                return this.totalMOFieldSpecified;
            }
            set {
                this.totalMOFieldSpecified = value;
                this.RaisePropertyChanged("totalMOSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public decimal totalMCL {
            get {
                return this.totalMCLField;
            }
            set {
                this.totalMCLField = value;
                this.RaisePropertyChanged("totalMCL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalMCLSpecified {
            get {
                return this.totalMCLFieldSpecified;
            }
            set {
                this.totalMCLFieldSpecified = value;
                this.RaisePropertyChanged("totalMCLSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("itemsPresupuestarios", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=28)]
        public itemPresupuestarioRecursosBean[] itemsPresupuestarios {
            get {
                return this.itemsPresupuestariosField;
            }
            set {
                this.itemsPresupuestariosField = value;
                this.RaisePropertyChanged("itemsPresupuestarios");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("itemsNoPresupuestarios", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=29)]
        public itemNoPresupuestarioRecursosBean[] itemsNoPresupuestarios {
            get {
                return this.itemsNoPresupuestariosField;
            }
            set {
                this.itemsNoPresupuestariosField = value;
                this.RaisePropertyChanged("itemsNoPresupuestarios");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bean.webService.common.recursos.esidif.mecon.gov.ar")]
    public partial class emisorBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoFuncionalField;
        
        private string tipoEntidadOperativaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigoFuncional {
            get {
                return this.codigoFuncionalField;
            }
            set {
                this.codigoFuncionalField = value;
                this.RaisePropertyChanged("codigoFuncional");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string tipoEntidadOperativa {
            get {
                return this.tipoEntidadOperativaField;
            }
            set {
                this.tipoEntidadOperativaField = value;
                this.RaisePropertyChanged("tipoEntidadOperativa");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bean.webService.common.recursos.esidif.mecon.gov.ar")]
    public partial class generarComprobanteRecursosResponseBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private emisorBean entidadEmisoraField;
        
        private long ejercicioNovedadField;
        
        private bool ejercicioNovedadFieldSpecified;
        
        private long numeroNovedadField;
        
        private bool numeroNovedadFieldSpecified;
        
        private string estadoNovedadField;
        
        private string motivoErrorField;
        
        private comprobanteRegistroBean comprobanteRegistroField;
        
        private long periodoImpactoField;
        
        private bool periodoImpactoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public emisorBean entidadEmisora {
            get {
                return this.entidadEmisoraField;
            }
            set {
                this.entidadEmisoraField = value;
                this.RaisePropertyChanged("entidadEmisora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long ejercicioNovedad {
            get {
                return this.ejercicioNovedadField;
            }
            set {
                this.ejercicioNovedadField = value;
                this.RaisePropertyChanged("ejercicioNovedad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ejercicioNovedadSpecified {
            get {
                return this.ejercicioNovedadFieldSpecified;
            }
            set {
                this.ejercicioNovedadFieldSpecified = value;
                this.RaisePropertyChanged("ejercicioNovedadSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long numeroNovedad {
            get {
                return this.numeroNovedadField;
            }
            set {
                this.numeroNovedadField = value;
                this.RaisePropertyChanged("numeroNovedad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroNovedadSpecified {
            get {
                return this.numeroNovedadFieldSpecified;
            }
            set {
                this.numeroNovedadFieldSpecified = value;
                this.RaisePropertyChanged("numeroNovedadSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string estadoNovedad {
            get {
                return this.estadoNovedadField;
            }
            set {
                this.estadoNovedadField = value;
                this.RaisePropertyChanged("estadoNovedad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string motivoError {
            get {
                return this.motivoErrorField;
            }
            set {
                this.motivoErrorField = value;
                this.RaisePropertyChanged("motivoError");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public comprobanteRegistroBean comprobanteRegistro {
            get {
                return this.comprobanteRegistroField;
            }
            set {
                this.comprobanteRegistroField = value;
                this.RaisePropertyChanged("comprobanteRegistro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public long periodoImpacto {
            get {
                return this.periodoImpactoField;
            }
            set {
                this.periodoImpactoField = value;
                this.RaisePropertyChanged("periodoImpacto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool periodoImpactoSpecified {
            get {
                return this.periodoImpactoFieldSpecified;
            }
            set {
                this.periodoImpactoFieldSpecified = value;
                this.RaisePropertyChanged("periodoImpactoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bean.webService.common.recursos.esidif.mecon.gov.ar")]
    public partial class comprobanteRegistroBean : comprobanteEjecucionBean {
        
        private string tipoRegistroField;
        
        private string etapaField;
        
        private System.DateTime fechaRegistroField;
        
        private bool fechaRegistroFieldSpecified;
        
        private string monedaOrigenField;
        
        private bool esInicioVinculoField;
        
        private bool esInicioVinculoFieldSpecified;
        
        private comprobanteOperacionVinculadaBean comprobanteVinculoField;
        
        private decimal totalMOField;
        
        private bool totalMOFieldSpecified;
        
        private decimal totalMCLField;
        
        private bool totalMCLFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string tipoRegistro {
            get {
                return this.tipoRegistroField;
            }
            set {
                this.tipoRegistroField = value;
                this.RaisePropertyChanged("tipoRegistro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string etapa {
            get {
                return this.etapaField;
            }
            set {
                this.etapaField = value;
                this.RaisePropertyChanged("etapa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaRegistro {
            get {
                return this.fechaRegistroField;
            }
            set {
                this.fechaRegistroField = value;
                this.RaisePropertyChanged("fechaRegistro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaRegistroSpecified {
            get {
                return this.fechaRegistroFieldSpecified;
            }
            set {
                this.fechaRegistroFieldSpecified = value;
                this.RaisePropertyChanged("fechaRegistroSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string monedaOrigen {
            get {
                return this.monedaOrigenField;
            }
            set {
                this.monedaOrigenField = value;
                this.RaisePropertyChanged("monedaOrigen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public bool esInicioVinculo {
            get {
                return this.esInicioVinculoField;
            }
            set {
                this.esInicioVinculoField = value;
                this.RaisePropertyChanged("esInicioVinculo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool esInicioVinculoSpecified {
            get {
                return this.esInicioVinculoFieldSpecified;
            }
            set {
                this.esInicioVinculoFieldSpecified = value;
                this.RaisePropertyChanged("esInicioVinculoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public comprobanteOperacionVinculadaBean comprobanteVinculo {
            get {
                return this.comprobanteVinculoField;
            }
            set {
                this.comprobanteVinculoField = value;
                this.RaisePropertyChanged("comprobanteVinculo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public decimal totalMO {
            get {
                return this.totalMOField;
            }
            set {
                this.totalMOField = value;
                this.RaisePropertyChanged("totalMO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalMOSpecified {
            get {
                return this.totalMOFieldSpecified;
            }
            set {
                this.totalMOFieldSpecified = value;
                this.RaisePropertyChanged("totalMOSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public decimal totalMCL {
            get {
                return this.totalMCLField;
            }
            set {
                this.totalMCLField = value;
                this.RaisePropertyChanged("totalMCL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalMCLSpecified {
            get {
                return this.totalMCLFieldSpecified;
            }
            set {
                this.totalMCLFieldSpecified = value;
                this.RaisePropertyChanged("totalMCLSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bean.webService.common.recursos.esidif.mecon.gov.ar")]
    public partial class comprobanteOperacionVinculadaBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private emisorBean entidadEmisoraField;
        
        private string tipoComprobanteField;
        
        private long ejercicioField;
        
        private bool ejercicioFieldSpecified;
        
        private long numeroComprobanteField;
        
        private bool numeroComprobanteFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public emisorBean entidadEmisora {
            get {
                return this.entidadEmisoraField;
            }
            set {
                this.entidadEmisoraField = value;
                this.RaisePropertyChanged("entidadEmisora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string tipoComprobante {
            get {
                return this.tipoComprobanteField;
            }
            set {
                this.tipoComprobanteField = value;
                this.RaisePropertyChanged("tipoComprobante");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long ejercicio {
            get {
                return this.ejercicioField;
            }
            set {
                this.ejercicioField = value;
                this.RaisePropertyChanged("ejercicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ejercicioSpecified {
            get {
                return this.ejercicioFieldSpecified;
            }
            set {
                this.ejercicioFieldSpecified = value;
                this.RaisePropertyChanged("ejercicioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public long numeroComprobante {
            get {
                return this.numeroComprobanteField;
            }
            set {
                this.numeroComprobanteField = value;
                this.RaisePropertyChanged("numeroComprobante");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroComprobanteSpecified {
            get {
                return this.numeroComprobanteFieldSpecified;
            }
            set {
                this.numeroComprobanteFieldSpecified = value;
                this.RaisePropertyChanged("numeroComprobanteSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(comprobanteRegistroBean))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bean.webService.common.recursos.esidif.mecon.gov.ar")]
    public partial class comprobanteEjecucionBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private emisorBean entidadEmisoraField;
        
        private long ejercicioField;
        
        private bool ejercicioFieldSpecified;
        
        private string tipoComprobanteField;
        
        private long numeroComprobanteField;
        
        private bool numeroComprobanteFieldSpecified;
        
        private long nroSidifField;
        
        private bool nroSidifFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public emisorBean entidadEmisora {
            get {
                return this.entidadEmisoraField;
            }
            set {
                this.entidadEmisoraField = value;
                this.RaisePropertyChanged("entidadEmisora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long ejercicio {
            get {
                return this.ejercicioField;
            }
            set {
                this.ejercicioField = value;
                this.RaisePropertyChanged("ejercicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ejercicioSpecified {
            get {
                return this.ejercicioFieldSpecified;
            }
            set {
                this.ejercicioFieldSpecified = value;
                this.RaisePropertyChanged("ejercicioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string tipoComprobante {
            get {
                return this.tipoComprobanteField;
            }
            set {
                this.tipoComprobanteField = value;
                this.RaisePropertyChanged("tipoComprobante");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public long numeroComprobante {
            get {
                return this.numeroComprobanteField;
            }
            set {
                this.numeroComprobanteField = value;
                this.RaisePropertyChanged("numeroComprobante");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroComprobanteSpecified {
            get {
                return this.numeroComprobanteFieldSpecified;
            }
            set {
                this.numeroComprobanteFieldSpecified = value;
                this.RaisePropertyChanged("numeroComprobanteSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public long nroSidif {
            get {
                return this.nroSidifField;
            }
            set {
                this.nroSidifField = value;
                this.RaisePropertyChanged("nroSidif");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nroSidifSpecified {
            get {
                return this.nroSidifFieldSpecified;
            }
            set {
                this.nroSidifFieldSpecified = value;
                this.RaisePropertyChanged("nroSidifSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bean.webService.common.recursos.esidif.mecon.gov.ar")]
    public partial class rubroRecursoBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long tipoField;
        
        private bool tipoFieldSpecified;
        
        private long claseField;
        
        private bool claseFieldSpecified;
        
        private long conceptoField;
        
        private bool conceptoFieldSpecified;
        
        private long subconceptoField;
        
        private bool subconceptoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoSpecified {
            get {
                return this.tipoFieldSpecified;
            }
            set {
                this.tipoFieldSpecified = value;
                this.RaisePropertyChanged("tipoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long clase {
            get {
                return this.claseField;
            }
            set {
                this.claseField = value;
                this.RaisePropertyChanged("clase");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool claseSpecified {
            get {
                return this.claseFieldSpecified;
            }
            set {
                this.claseFieldSpecified = value;
                this.RaisePropertyChanged("claseSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long concepto {
            get {
                return this.conceptoField;
            }
            set {
                this.conceptoField = value;
                this.RaisePropertyChanged("concepto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool conceptoSpecified {
            get {
                return this.conceptoFieldSpecified;
            }
            set {
                this.conceptoFieldSpecified = value;
                this.RaisePropertyChanged("conceptoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public long subconcepto {
            get {
                return this.subconceptoField;
            }
            set {
                this.subconceptoField = value;
                this.RaisePropertyChanged("subconcepto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool subconceptoSpecified {
            get {
                return this.subconceptoFieldSpecified;
            }
            set {
                this.subconceptoFieldSpecified = value;
                this.RaisePropertyChanged("subconceptoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bean.webService.common.recursos.esidif.mecon.gov.ar")]
    public partial class fuenteFinanciamientoBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long procedenciaField;
        
        private bool procedenciaFieldSpecified;
        
        private long fuenteField;
        
        private bool fuenteFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long procedencia {
            get {
                return this.procedenciaField;
            }
            set {
                this.procedenciaField = value;
                this.RaisePropertyChanged("procedencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool procedenciaSpecified {
            get {
                return this.procedenciaFieldSpecified;
            }
            set {
                this.procedenciaFieldSpecified = value;
                this.RaisePropertyChanged("procedenciaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long fuente {
            get {
                return this.fuenteField;
            }
            set {
                this.fuenteField = value;
                this.RaisePropertyChanged("fuente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fuenteSpecified {
            get {
                return this.fuenteFieldSpecified;
            }
            set {
                this.fuenteFieldSpecified = value;
                this.RaisePropertyChanged("fuenteSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bean.webService.common.recursos.esidif.mecon.gov.ar")]
    public partial class conceptoIngresoBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private emisorBean entidadEmisoraField;
        
        private long conceptoField;
        
        private bool conceptoFieldSpecified;
        
        private long subconceptoField;
        
        private bool subconceptoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public emisorBean entidadEmisora {
            get {
                return this.entidadEmisoraField;
            }
            set {
                this.entidadEmisoraField = value;
                this.RaisePropertyChanged("entidadEmisora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long concepto {
            get {
                return this.conceptoField;
            }
            set {
                this.conceptoField = value;
                this.RaisePropertyChanged("concepto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool conceptoSpecified {
            get {
                return this.conceptoFieldSpecified;
            }
            set {
                this.conceptoFieldSpecified = value;
                this.RaisePropertyChanged("conceptoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long subconcepto {
            get {
                return this.subconceptoField;
            }
            set {
                this.subconceptoField = value;
                this.RaisePropertyChanged("subconcepto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool subconceptoSpecified {
            get {
                return this.subconceptoFieldSpecified;
            }
            set {
                this.subconceptoFieldSpecified = value;
                this.RaisePropertyChanged("subconceptoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(itemNoPresupuestarioRecursosBean))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(itemPresupuestarioRecursosBean))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bean.webService.common.recursos.esidif.mecon.gov.ar")]
    public partial class itemRecursosBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private comprobanteEjecucionBean comprobanteDevengadoField;
        
        private conceptoIngresoBean conceptoIngresosField;
        
        private decimal importeMOField;
        
        private bool importeMOFieldSpecified;
        
        private decimal importeMCLField;
        
        private bool importeMCLFieldSpecified;
        
        private long prestamoExternoField;
        
        private bool prestamoExternoFieldSpecified;
        
        private string recacField;
        
        private string sigadeField;
        
        private string cotenaField;
        
        private long safField;
        
        private bool safFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public comprobanteEjecucionBean comprobanteDevengado {
            get {
                return this.comprobanteDevengadoField;
            }
            set {
                this.comprobanteDevengadoField = value;
                this.RaisePropertyChanged("comprobanteDevengado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public conceptoIngresoBean conceptoIngresos {
            get {
                return this.conceptoIngresosField;
            }
            set {
                this.conceptoIngresosField = value;
                this.RaisePropertyChanged("conceptoIngresos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal importeMO {
            get {
                return this.importeMOField;
            }
            set {
                this.importeMOField = value;
                this.RaisePropertyChanged("importeMO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool importeMOSpecified {
            get {
                return this.importeMOFieldSpecified;
            }
            set {
                this.importeMOFieldSpecified = value;
                this.RaisePropertyChanged("importeMOSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal importeMCL {
            get {
                return this.importeMCLField;
            }
            set {
                this.importeMCLField = value;
                this.RaisePropertyChanged("importeMCL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool importeMCLSpecified {
            get {
                return this.importeMCLFieldSpecified;
            }
            set {
                this.importeMCLFieldSpecified = value;
                this.RaisePropertyChanged("importeMCLSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public long prestamoExterno {
            get {
                return this.prestamoExternoField;
            }
            set {
                this.prestamoExternoField = value;
                this.RaisePropertyChanged("prestamoExterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool prestamoExternoSpecified {
            get {
                return this.prestamoExternoFieldSpecified;
            }
            set {
                this.prestamoExternoFieldSpecified = value;
                this.RaisePropertyChanged("prestamoExternoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string recac {
            get {
                return this.recacField;
            }
            set {
                this.recacField = value;
                this.RaisePropertyChanged("recac");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string sigade {
            get {
                return this.sigadeField;
            }
            set {
                this.sigadeField = value;
                this.RaisePropertyChanged("sigade");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string cotena {
            get {
                return this.cotenaField;
            }
            set {
                this.cotenaField = value;
                this.RaisePropertyChanged("cotena");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public long saf {
            get {
                return this.safField;
            }
            set {
                this.safField = value;
                this.RaisePropertyChanged("saf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool safSpecified {
            get {
                return this.safFieldSpecified;
            }
            set {
                this.safFieldSpecified = value;
                this.RaisePropertyChanged("safSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bean.webService.common.recursos.esidif.mecon.gov.ar")]
    public partial class itemNoPresupuestarioRecursosBean : itemRecursosBean {
        
        private long axtField;
        
        private bool axtFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long axt {
            get {
                return this.axtField;
            }
            set {
                this.axtField = value;
                this.RaisePropertyChanged("axt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool axtSpecified {
            get {
                return this.axtFieldSpecified;
            }
            set {
                this.axtFieldSpecified = value;
                this.RaisePropertyChanged("axtSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bean.webService.common.recursos.esidif.mecon.gov.ar")]
    public partial class itemPresupuestarioRecursosBean : itemRecursosBean {
        
        private string unidadDescentralizadaField;
        
        private fuenteFinanciamientoBean fuenteFinanciamientoField;
        
        private rubroRecursoBean rubroRecursoField;
        
        private long entidadOrigenField;
        
        private bool entidadOrigenFieldSpecified;
        
        private long monedaField;
        
        private bool monedaFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string unidadDescentralizada {
            get {
                return this.unidadDescentralizadaField;
            }
            set {
                this.unidadDescentralizadaField = value;
                this.RaisePropertyChanged("unidadDescentralizada");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public fuenteFinanciamientoBean fuenteFinanciamiento {
            get {
                return this.fuenteFinanciamientoField;
            }
            set {
                this.fuenteFinanciamientoField = value;
                this.RaisePropertyChanged("fuenteFinanciamiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public rubroRecursoBean rubroRecurso {
            get {
                return this.rubroRecursoField;
            }
            set {
                this.rubroRecursoField = value;
                this.RaisePropertyChanged("rubroRecurso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public long entidadOrigen {
            get {
                return this.entidadOrigenField;
            }
            set {
                this.entidadOrigenField = value;
                this.RaisePropertyChanged("entidadOrigen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool entidadOrigenSpecified {
            get {
                return this.entidadOrigenFieldSpecified;
            }
            set {
                this.entidadOrigenFieldSpecified = value;
                this.RaisePropertyChanged("entidadOrigenSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public long moneda {
            get {
                return this.monedaField;
            }
            set {
                this.monedaField = value;
                this.RaisePropertyChanged("moneda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool monedaSpecified {
            get {
                return this.monedaFieldSpecified;
            }
            set {
                this.monedaFieldSpecified = value;
                this.RaisePropertyChanged("monedaSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bean.webService.common.recursos.esidif.mecon.gov.ar")]
    public partial class identificacionDeTramiteBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string identificacionDeTramiteField;
        
        private string tipoField;
        
        private long anioField;
        
        private bool anioFieldSpecified;
        
        private emisorBean entidadEmisoraField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string identificacionDeTramite {
            get {
                return this.identificacionDeTramiteField;
            }
            set {
                this.identificacionDeTramiteField = value;
                this.RaisePropertyChanged("identificacionDeTramite");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long anio {
            get {
                return this.anioField;
            }
            set {
                this.anioField = value;
                this.RaisePropertyChanged("anio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool anioSpecified {
            get {
                return this.anioFieldSpecified;
            }
            set {
                this.anioFieldSpecified = value;
                this.RaisePropertyChanged("anioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public emisorBean entidadEmisora {
            get {
                return this.entidadEmisoraField;
            }
            set {
                this.entidadEmisoraField = value;
                this.RaisePropertyChanged("entidadEmisora");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bean.webService.common.recursos.esidif.mecon.gov.ar")]
    public partial class documentoRespaldatorioBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string documentoGestionField;
        
        private long ejercicioDocumentoField;
        
        private bool ejercicioDocumentoFieldSpecified;
        
        private long nroDocumentoField;
        
        private bool nroDocumentoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string documentoGestion {
            get {
                return this.documentoGestionField;
            }
            set {
                this.documentoGestionField = value;
                this.RaisePropertyChanged("documentoGestion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long ejercicioDocumento {
            get {
                return this.ejercicioDocumentoField;
            }
            set {
                this.ejercicioDocumentoField = value;
                this.RaisePropertyChanged("ejercicioDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ejercicioDocumentoSpecified {
            get {
                return this.ejercicioDocumentoFieldSpecified;
            }
            set {
                this.ejercicioDocumentoFieldSpecified = value;
                this.RaisePropertyChanged("ejercicioDocumentoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long nroDocumento {
            get {
                return this.nroDocumentoField;
            }
            set {
                this.nroDocumentoField = value;
                this.RaisePropertyChanged("nroDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nroDocumentoSpecified {
            get {
                return this.nroDocumentoFieldSpecified;
            }
            set {
                this.nroDocumentoFieldSpecified = value;
                this.RaisePropertyChanged("nroDocumentoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bean.webService.common.recursos.esidif.mecon.gov.ar")]
    public partial class cotizacionBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime fechaCotizacionField;
        
        private bool fechaCotizacionFieldSpecified;
        
        private string tipoMonedaField;
        
        private decimal valorField;
        
        private bool valorFieldSpecified;
        
        private string tipoCotizacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime fechaCotizacion {
            get {
                return this.fechaCotizacionField;
            }
            set {
                this.fechaCotizacionField = value;
                this.RaisePropertyChanged("fechaCotizacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaCotizacionSpecified {
            get {
                return this.fechaCotizacionFieldSpecified;
            }
            set {
                this.fechaCotizacionFieldSpecified = value;
                this.RaisePropertyChanged("fechaCotizacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string tipoMoneda {
            get {
                return this.tipoMonedaField;
            }
            set {
                this.tipoMonedaField = value;
                this.RaisePropertyChanged("tipoMoneda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
                this.RaisePropertyChanged("valor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valorSpecified {
            get {
                return this.valorFieldSpecified;
            }
            set {
                this.valorFieldSpecified = value;
                this.RaisePropertyChanged("valorSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string tipoCotizacion {
            get {
                return this.tipoCotizacionField;
            }
            set {
                this.tipoCotizacionField = value;
                this.RaisePropertyChanged("tipoCotizacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bean.webService.common.recursos.esidif.mecon.gov.ar")]
    public partial class cuentaOperativaBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long codigoBancoField;
        
        private bool codigoBancoFieldSpecified;
        
        private string codigoSucursalField;
        
        private string codigoCuentaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long codigoBanco {
            get {
                return this.codigoBancoField;
            }
            set {
                this.codigoBancoField = value;
                this.RaisePropertyChanged("codigoBanco");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoBancoSpecified {
            get {
                return this.codigoBancoFieldSpecified;
            }
            set {
                this.codigoBancoFieldSpecified = value;
                this.RaisePropertyChanged("codigoBancoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string codigoSucursal {
            get {
                return this.codigoSucursalField;
            }
            set {
                this.codigoSucursalField = value;
                this.RaisePropertyChanged("codigoSucursal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string codigoCuenta {
            get {
                return this.codigoCuentaField;
            }
            set {
                this.codigoCuentaField = value;
                this.RaisePropertyChanged("codigoCuenta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bean.webService.common.recursos.esidif.mecon.gov.ar")]
    public partial class donacionBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private emisorBean entidadEmisoraField;
        
        private string codigoDonacionField;
        
        private long numeroDonacionField;
        
        private bool numeroDonacionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public emisorBean entidadEmisora {
            get {
                return this.entidadEmisoraField;
            }
            set {
                this.entidadEmisoraField = value;
                this.RaisePropertyChanged("entidadEmisora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string codigoDonacion {
            get {
                return this.codigoDonacionField;
            }
            set {
                this.codigoDonacionField = value;
                this.RaisePropertyChanged("codigoDonacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long numeroDonacion {
            get {
                return this.numeroDonacionField;
            }
            set {
                this.numeroDonacionField = value;
                this.RaisePropertyChanged("numeroDonacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroDonacionSpecified {
            get {
                return this.numeroDonacionFieldSpecified;
            }
            set {
                this.numeroDonacionFieldSpecified = value;
                this.RaisePropertyChanged("numeroDonacionSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generarComprobanteRecursosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bean.webService.common.recursos.esidif.mecon.gov.ar", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ESIDIFRecursos.service.comprobanteRecursosBean comprobanteRecursos;
        
        public generarComprobanteRecursosRequest() {
        }
        
        public generarComprobanteRecursosRequest(ESIDIFRecursos.service.comprobanteRecursosBean comprobanteRecursos) {
            this.comprobanteRecursos = comprobanteRecursos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generarComprobanteRecursosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bean.webService.common.recursos.esidif.mecon.gov.ar", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ESIDIFRecursos.service.generarComprobanteRecursosResponseBean generarComprobanteRecursos;
        
        public generarComprobanteRecursosResponse() {
        }
        
        public generarComprobanteRecursosResponse(ESIDIFRecursos.service.generarComprobanteRecursosResponseBean generarComprobanteRecursos) {
            this.generarComprobanteRecursos = generarComprobanteRecursos;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface generarComprobanteRecursosServiceChannel : ESIDIFRecursos.service.generarComprobanteRecursosService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class generarComprobanteRecursosServiceClient : System.ServiceModel.ClientBase<ESIDIFRecursos.service.generarComprobanteRecursosService>, ESIDIFRecursos.service.generarComprobanteRecursosService {
        
        public generarComprobanteRecursosServiceClient() {
        }
        
        public generarComprobanteRecursosServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public generarComprobanteRecursosServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public generarComprobanteRecursosServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public generarComprobanteRecursosServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ESIDIFRecursos.service.generarComprobanteRecursosResponse ESIDIFRecursos.service.generarComprobanteRecursosService.generarComprobanteRecursos(ESIDIFRecursos.service.generarComprobanteRecursosRequest request) {
            return base.Channel.generarComprobanteRecursos(request);
        }
        
        public ESIDIFRecursos.service.generarComprobanteRecursosResponseBean generarComprobanteRecursos(ESIDIFRecursos.service.comprobanteRecursosBean comprobanteRecursos) {
            ESIDIFRecursos.service.generarComprobanteRecursosRequest inValue = new ESIDIFRecursos.service.generarComprobanteRecursosRequest();
            inValue.comprobanteRecursos = comprobanteRecursos;
            ESIDIFRecursos.service.generarComprobanteRecursosResponse retVal = ((ESIDIFRecursos.service.generarComprobanteRecursosService)(this)).generarComprobanteRecursos(inValue);
            return retVal.generarComprobanteRecursos;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ESIDIFRecursos.service.generarComprobanteRecursosResponse> ESIDIFRecursos.service.generarComprobanteRecursosService.generarComprobanteRecursosAsync(ESIDIFRecursos.service.generarComprobanteRecursosRequest request) {
            return base.Channel.generarComprobanteRecursosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ESIDIFRecursos.service.generarComprobanteRecursosResponse> generarComprobanteRecursosAsync(ESIDIFRecursos.service.comprobanteRecursosBean comprobanteRecursos) {
            ESIDIFRecursos.service.generarComprobanteRecursosRequest inValue = new ESIDIFRecursos.service.generarComprobanteRecursosRequest();
            inValue.comprobanteRecursos = comprobanteRecursos;
            return ((ESIDIFRecursos.service.generarComprobanteRecursosService)(this)).generarComprobanteRecursosAsync(inValue);
        }
    }
}
